// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notifications.proto

#ifndef PROTOBUF_INCLUDED_notifications_2eproto
#define PROTOBUF_INCLUDED_notifications_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_notifications_2eproto 

namespace protobuf_notifications_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_notifications_2eproto
namespace open_vario {
class AltitudeNotification;
class AltitudeNotificationDefaultTypeInternal;
extern AltitudeNotificationDefaultTypeInternal _AltitudeNotification_default_instance_;
class NavigationNotification;
class NavigationNotificationDefaultTypeInternal;
extern NavigationNotificationDefaultTypeInternal _NavigationNotification_default_instance_;
class PressureNotification;
class PressureNotificationDefaultTypeInternal;
extern PressureNotificationDefaultTypeInternal _PressureNotification_default_instance_;
class SimuNotification;
class SimuNotificationDefaultTypeInternal;
extern SimuNotificationDefaultTypeInternal _SimuNotification_default_instance_;
class StartNotification;
class StartNotificationDefaultTypeInternal;
extern StartNotificationDefaultTypeInternal _StartNotification_default_instance_;
class TemperatureNotification;
class TemperatureNotificationDefaultTypeInternal;
extern TemperatureNotificationDefaultTypeInternal _TemperatureNotification_default_instance_;
class VarioNotification;
class VarioNotificationDefaultTypeInternal;
extern VarioNotificationDefaultTypeInternal _VarioNotification_default_instance_;
}  // namespace open_vario
namespace google {
namespace protobuf {
template<> ::open_vario::AltitudeNotification* Arena::CreateMaybeMessage<::open_vario::AltitudeNotification>(Arena*);
template<> ::open_vario::NavigationNotification* Arena::CreateMaybeMessage<::open_vario::NavigationNotification>(Arena*);
template<> ::open_vario::PressureNotification* Arena::CreateMaybeMessage<::open_vario::PressureNotification>(Arena*);
template<> ::open_vario::SimuNotification* Arena::CreateMaybeMessage<::open_vario::SimuNotification>(Arena*);
template<> ::open_vario::StartNotification* Arena::CreateMaybeMessage<::open_vario::StartNotification>(Arena*);
template<> ::open_vario::TemperatureNotification* Arena::CreateMaybeMessage<::open_vario::TemperatureNotification>(Arena*);
template<> ::open_vario::VarioNotification* Arena::CreateMaybeMessage<::open_vario::VarioNotification>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace open_vario {

// ===================================================================

class StartNotification : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:open_vario.StartNotification) */ {
 public:
  StartNotification();
  virtual ~StartNotification();

  StartNotification(const StartNotification& from);

  inline StartNotification& operator=(const StartNotification& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StartNotification(StartNotification&& from) noexcept
    : StartNotification() {
    *this = ::std::move(from);
  }

  inline StartNotification& operator=(StartNotification&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StartNotification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StartNotification* internal_default_instance() {
    return reinterpret_cast<const StartNotification*>(
               &_StartNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(StartNotification* other);
  friend void swap(StartNotification& a, StartNotification& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StartNotification* New() const final {
    return CreateMaybeMessage<StartNotification>(NULL);
  }

  StartNotification* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StartNotification>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StartNotification& from);
  void MergeFrom(const StartNotification& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StartNotification* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:open_vario.StartNotification)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notifications_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PressureNotification : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:open_vario.PressureNotification) */ {
 public:
  PressureNotification();
  virtual ~PressureNotification();

  PressureNotification(const PressureNotification& from);

  inline PressureNotification& operator=(const PressureNotification& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PressureNotification(PressureNotification&& from) noexcept
    : PressureNotification() {
    *this = ::std::move(from);
  }

  inline PressureNotification& operator=(PressureNotification&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PressureNotification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PressureNotification* internal_default_instance() {
    return reinterpret_cast<const PressureNotification*>(
               &_PressureNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(PressureNotification* other);
  friend void swap(PressureNotification& a, PressureNotification& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PressureNotification* New() const final {
    return CreateMaybeMessage<PressureNotification>(NULL);
  }

  PressureNotification* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PressureNotification>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PressureNotification& from);
  void MergeFrom(const PressureNotification& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PressureNotification* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 pressure = 1;
  void clear_pressure();
  static const int kPressureFieldNumber = 1;
  ::google::protobuf::uint32 pressure() const;
  void set_pressure(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:open_vario.PressureNotification)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 pressure_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notifications_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TemperatureNotification : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:open_vario.TemperatureNotification) */ {
 public:
  TemperatureNotification();
  virtual ~TemperatureNotification();

  TemperatureNotification(const TemperatureNotification& from);

  inline TemperatureNotification& operator=(const TemperatureNotification& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TemperatureNotification(TemperatureNotification&& from) noexcept
    : TemperatureNotification() {
    *this = ::std::move(from);
  }

  inline TemperatureNotification& operator=(TemperatureNotification&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TemperatureNotification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TemperatureNotification* internal_default_instance() {
    return reinterpret_cast<const TemperatureNotification*>(
               &_TemperatureNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(TemperatureNotification* other);
  friend void swap(TemperatureNotification& a, TemperatureNotification& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TemperatureNotification* New() const final {
    return CreateMaybeMessage<TemperatureNotification>(NULL);
  }

  TemperatureNotification* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TemperatureNotification>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TemperatureNotification& from);
  void MergeFrom(const TemperatureNotification& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TemperatureNotification* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // sint32 temperature = 1;
  void clear_temperature();
  static const int kTemperatureFieldNumber = 1;
  ::google::protobuf::int32 temperature() const;
  void set_temperature(::google::protobuf::int32 value);

  // sint32 min_temperature = 2;
  void clear_min_temperature();
  static const int kMinTemperatureFieldNumber = 2;
  ::google::protobuf::int32 min_temperature() const;
  void set_min_temperature(::google::protobuf::int32 value);

  // sint32 max_temperature = 3;
  void clear_max_temperature();
  static const int kMaxTemperatureFieldNumber = 3;
  ::google::protobuf::int32 max_temperature() const;
  void set_max_temperature(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:open_vario.TemperatureNotification)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 temperature_;
  ::google::protobuf::int32 min_temperature_;
  ::google::protobuf::int32 max_temperature_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notifications_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AltitudeNotification : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:open_vario.AltitudeNotification) */ {
 public:
  AltitudeNotification();
  virtual ~AltitudeNotification();

  AltitudeNotification(const AltitudeNotification& from);

  inline AltitudeNotification& operator=(const AltitudeNotification& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AltitudeNotification(AltitudeNotification&& from) noexcept
    : AltitudeNotification() {
    *this = ::std::move(from);
  }

  inline AltitudeNotification& operator=(AltitudeNotification&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AltitudeNotification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AltitudeNotification* internal_default_instance() {
    return reinterpret_cast<const AltitudeNotification*>(
               &_AltitudeNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(AltitudeNotification* other);
  friend void swap(AltitudeNotification& a, AltitudeNotification& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AltitudeNotification* New() const final {
    return CreateMaybeMessage<AltitudeNotification>(NULL);
  }

  AltitudeNotification* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AltitudeNotification>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AltitudeNotification& from);
  void MergeFrom(const AltitudeNotification& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AltitudeNotification* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // sint32 main_altitude = 1;
  void clear_main_altitude();
  static const int kMainAltitudeFieldNumber = 1;
  ::google::protobuf::int32 main_altitude() const;
  void set_main_altitude(::google::protobuf::int32 value);

  // sint32 altitude_1 = 2;
  void clear_altitude_1();
  static const int kAltitude1FieldNumber = 2;
  ::google::protobuf::int32 altitude_1() const;
  void set_altitude_1(::google::protobuf::int32 value);

  // sint32 altitude_2 = 3;
  void clear_altitude_2();
  static const int kAltitude2FieldNumber = 3;
  ::google::protobuf::int32 altitude_2() const;
  void set_altitude_2(::google::protobuf::int32 value);

  // sint32 altitude_3 = 4;
  void clear_altitude_3();
  static const int kAltitude3FieldNumber = 4;
  ::google::protobuf::int32 altitude_3() const;
  void set_altitude_3(::google::protobuf::int32 value);

  // sint32 altitude_4 = 5;
  void clear_altitude_4();
  static const int kAltitude4FieldNumber = 5;
  ::google::protobuf::int32 altitude_4() const;
  void set_altitude_4(::google::protobuf::int32 value);

  // sint32 min_altitude = 6;
  void clear_min_altitude();
  static const int kMinAltitudeFieldNumber = 6;
  ::google::protobuf::int32 min_altitude() const;
  void set_min_altitude(::google::protobuf::int32 value);

  // sint32 max_altitude = 7;
  void clear_max_altitude();
  static const int kMaxAltitudeFieldNumber = 7;
  ::google::protobuf::int32 max_altitude() const;
  void set_max_altitude(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:open_vario.AltitudeNotification)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 main_altitude_;
  ::google::protobuf::int32 altitude_1_;
  ::google::protobuf::int32 altitude_2_;
  ::google::protobuf::int32 altitude_3_;
  ::google::protobuf::int32 altitude_4_;
  ::google::protobuf::int32 min_altitude_;
  ::google::protobuf::int32 max_altitude_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notifications_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class VarioNotification : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:open_vario.VarioNotification) */ {
 public:
  VarioNotification();
  virtual ~VarioNotification();

  VarioNotification(const VarioNotification& from);

  inline VarioNotification& operator=(const VarioNotification& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  VarioNotification(VarioNotification&& from) noexcept
    : VarioNotification() {
    *this = ::std::move(from);
  }

  inline VarioNotification& operator=(VarioNotification&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const VarioNotification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VarioNotification* internal_default_instance() {
    return reinterpret_cast<const VarioNotification*>(
               &_VarioNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(VarioNotification* other);
  friend void swap(VarioNotification& a, VarioNotification& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline VarioNotification* New() const final {
    return CreateMaybeMessage<VarioNotification>(NULL);
  }

  VarioNotification* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<VarioNotification>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const VarioNotification& from);
  void MergeFrom(const VarioNotification& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VarioNotification* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // sint32 vario = 1;
  void clear_vario();
  static const int kVarioFieldNumber = 1;
  ::google::protobuf::int32 vario() const;
  void set_vario(::google::protobuf::int32 value);

  // sint32 min_vario = 2;
  void clear_min_vario();
  static const int kMinVarioFieldNumber = 2;
  ::google::protobuf::int32 min_vario() const;
  void set_min_vario(::google::protobuf::int32 value);

  // sint32 max_vario = 3;
  void clear_max_vario();
  static const int kMaxVarioFieldNumber = 3;
  ::google::protobuf::int32 max_vario() const;
  void set_max_vario(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:open_vario.VarioNotification)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 vario_;
  ::google::protobuf::int32 min_vario_;
  ::google::protobuf::int32 max_vario_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notifications_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NavigationNotification : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:open_vario.NavigationNotification) */ {
 public:
  NavigationNotification();
  virtual ~NavigationNotification();

  NavigationNotification(const NavigationNotification& from);

  inline NavigationNotification& operator=(const NavigationNotification& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NavigationNotification(NavigationNotification&& from) noexcept
    : NavigationNotification() {
    *this = ::std::move(from);
  }

  inline NavigationNotification& operator=(NavigationNotification&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NavigationNotification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NavigationNotification* internal_default_instance() {
    return reinterpret_cast<const NavigationNotification*>(
               &_NavigationNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(NavigationNotification* other);
  friend void swap(NavigationNotification& a, NavigationNotification& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NavigationNotification* New() const final {
    return CreateMaybeMessage<NavigationNotification>(NULL);
  }

  NavigationNotification* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NavigationNotification>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NavigationNotification& from);
  void MergeFrom(const NavigationNotification& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NavigationNotification* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double latitude = 2;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 2;
  double latitude() const;
  void set_latitude(double value);

  // sint32 speed = 1;
  void clear_speed();
  static const int kSpeedFieldNumber = 1;
  ::google::protobuf::int32 speed() const;
  void set_speed(::google::protobuf::int32 value);

  // uint32 track_angle = 4;
  void clear_track_angle();
  static const int kTrackAngleFieldNumber = 4;
  ::google::protobuf::uint32 track_angle() const;
  void set_track_angle(::google::protobuf::uint32 value);

  // double longitude = 3;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 3;
  double longitude() const;
  void set_longitude(double value);

  // sint32 min_speed = 5;
  void clear_min_speed();
  static const int kMinSpeedFieldNumber = 5;
  ::google::protobuf::int32 min_speed() const;
  void set_min_speed(::google::protobuf::int32 value);

  // sint32 max_speed = 6;
  void clear_max_speed();
  static const int kMaxSpeedFieldNumber = 6;
  ::google::protobuf::int32 max_speed() const;
  void set_max_speed(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:open_vario.NavigationNotification)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double latitude_;
  ::google::protobuf::int32 speed_;
  ::google::protobuf::uint32 track_angle_;
  double longitude_;
  ::google::protobuf::int32 min_speed_;
  ::google::protobuf::int32 max_speed_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notifications_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SimuNotification : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:open_vario.SimuNotification) */ {
 public:
  SimuNotification();
  virtual ~SimuNotification();

  SimuNotification(const SimuNotification& from);

  inline SimuNotification& operator=(const SimuNotification& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SimuNotification(SimuNotification&& from) noexcept
    : SimuNotification() {
    *this = ::std::move(from);
  }

  inline SimuNotification& operator=(SimuNotification&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SimuNotification& default_instance();

  enum NotificationsCase {
    kPressure = 1,
    kTemperature = 2,
    kAltitude = 3,
    kVario = 4,
    kNavigation = 5,
    NOTIFICATIONS_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SimuNotification* internal_default_instance() {
    return reinterpret_cast<const SimuNotification*>(
               &_SimuNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(SimuNotification* other);
  friend void swap(SimuNotification& a, SimuNotification& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SimuNotification* New() const final {
    return CreateMaybeMessage<SimuNotification>(NULL);
  }

  SimuNotification* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SimuNotification>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SimuNotification& from);
  void MergeFrom(const SimuNotification& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimuNotification* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .open_vario.PressureNotification pressure = 1;
  bool has_pressure() const;
  void clear_pressure();
  static const int kPressureFieldNumber = 1;
  private:
  const ::open_vario::PressureNotification& _internal_pressure() const;
  public:
  const ::open_vario::PressureNotification& pressure() const;
  ::open_vario::PressureNotification* release_pressure();
  ::open_vario::PressureNotification* mutable_pressure();
  void set_allocated_pressure(::open_vario::PressureNotification* pressure);

  // .open_vario.TemperatureNotification temperature = 2;
  bool has_temperature() const;
  void clear_temperature();
  static const int kTemperatureFieldNumber = 2;
  private:
  const ::open_vario::TemperatureNotification& _internal_temperature() const;
  public:
  const ::open_vario::TemperatureNotification& temperature() const;
  ::open_vario::TemperatureNotification* release_temperature();
  ::open_vario::TemperatureNotification* mutable_temperature();
  void set_allocated_temperature(::open_vario::TemperatureNotification* temperature);

  // .open_vario.AltitudeNotification altitude = 3;
  bool has_altitude() const;
  void clear_altitude();
  static const int kAltitudeFieldNumber = 3;
  private:
  const ::open_vario::AltitudeNotification& _internal_altitude() const;
  public:
  const ::open_vario::AltitudeNotification& altitude() const;
  ::open_vario::AltitudeNotification* release_altitude();
  ::open_vario::AltitudeNotification* mutable_altitude();
  void set_allocated_altitude(::open_vario::AltitudeNotification* altitude);

  // .open_vario.VarioNotification vario = 4;
  bool has_vario() const;
  void clear_vario();
  static const int kVarioFieldNumber = 4;
  private:
  const ::open_vario::VarioNotification& _internal_vario() const;
  public:
  const ::open_vario::VarioNotification& vario() const;
  ::open_vario::VarioNotification* release_vario();
  ::open_vario::VarioNotification* mutable_vario();
  void set_allocated_vario(::open_vario::VarioNotification* vario);

  // .open_vario.NavigationNotification navigation = 5;
  bool has_navigation() const;
  void clear_navigation();
  static const int kNavigationFieldNumber = 5;
  private:
  const ::open_vario::NavigationNotification& _internal_navigation() const;
  public:
  const ::open_vario::NavigationNotification& navigation() const;
  ::open_vario::NavigationNotification* release_navigation();
  ::open_vario::NavigationNotification* mutable_navigation();
  void set_allocated_navigation(::open_vario::NavigationNotification* navigation);

  void clear_Notifications();
  NotificationsCase Notifications_case() const;
  // @@protoc_insertion_point(class_scope:open_vario.SimuNotification)
 private:
  void set_has_pressure();
  void set_has_temperature();
  void set_has_altitude();
  void set_has_vario();
  void set_has_navigation();

  inline bool has_Notifications() const;
  inline void clear_has_Notifications();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  union NotificationsUnion {
    NotificationsUnion() {}
    ::open_vario::PressureNotification* pressure_;
    ::open_vario::TemperatureNotification* temperature_;
    ::open_vario::AltitudeNotification* altitude_;
    ::open_vario::VarioNotification* vario_;
    ::open_vario::NavigationNotification* navigation_;
  } Notifications_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::protobuf_notifications_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StartNotification

// -------------------------------------------------------------------

// PressureNotification

// uint32 pressure = 1;
inline void PressureNotification::clear_pressure() {
  pressure_ = 0u;
}
inline ::google::protobuf::uint32 PressureNotification::pressure() const {
  // @@protoc_insertion_point(field_get:open_vario.PressureNotification.pressure)
  return pressure_;
}
inline void PressureNotification::set_pressure(::google::protobuf::uint32 value) {
  
  pressure_ = value;
  // @@protoc_insertion_point(field_set:open_vario.PressureNotification.pressure)
}

// -------------------------------------------------------------------

// TemperatureNotification

// sint32 temperature = 1;
inline void TemperatureNotification::clear_temperature() {
  temperature_ = 0;
}
inline ::google::protobuf::int32 TemperatureNotification::temperature() const {
  // @@protoc_insertion_point(field_get:open_vario.TemperatureNotification.temperature)
  return temperature_;
}
inline void TemperatureNotification::set_temperature(::google::protobuf::int32 value) {
  
  temperature_ = value;
  // @@protoc_insertion_point(field_set:open_vario.TemperatureNotification.temperature)
}

// sint32 min_temperature = 2;
inline void TemperatureNotification::clear_min_temperature() {
  min_temperature_ = 0;
}
inline ::google::protobuf::int32 TemperatureNotification::min_temperature() const {
  // @@protoc_insertion_point(field_get:open_vario.TemperatureNotification.min_temperature)
  return min_temperature_;
}
inline void TemperatureNotification::set_min_temperature(::google::protobuf::int32 value) {
  
  min_temperature_ = value;
  // @@protoc_insertion_point(field_set:open_vario.TemperatureNotification.min_temperature)
}

// sint32 max_temperature = 3;
inline void TemperatureNotification::clear_max_temperature() {
  max_temperature_ = 0;
}
inline ::google::protobuf::int32 TemperatureNotification::max_temperature() const {
  // @@protoc_insertion_point(field_get:open_vario.TemperatureNotification.max_temperature)
  return max_temperature_;
}
inline void TemperatureNotification::set_max_temperature(::google::protobuf::int32 value) {
  
  max_temperature_ = value;
  // @@protoc_insertion_point(field_set:open_vario.TemperatureNotification.max_temperature)
}

// -------------------------------------------------------------------

// AltitudeNotification

// sint32 main_altitude = 1;
inline void AltitudeNotification::clear_main_altitude() {
  main_altitude_ = 0;
}
inline ::google::protobuf::int32 AltitudeNotification::main_altitude() const {
  // @@protoc_insertion_point(field_get:open_vario.AltitudeNotification.main_altitude)
  return main_altitude_;
}
inline void AltitudeNotification::set_main_altitude(::google::protobuf::int32 value) {
  
  main_altitude_ = value;
  // @@protoc_insertion_point(field_set:open_vario.AltitudeNotification.main_altitude)
}

// sint32 altitude_1 = 2;
inline void AltitudeNotification::clear_altitude_1() {
  altitude_1_ = 0;
}
inline ::google::protobuf::int32 AltitudeNotification::altitude_1() const {
  // @@protoc_insertion_point(field_get:open_vario.AltitudeNotification.altitude_1)
  return altitude_1_;
}
inline void AltitudeNotification::set_altitude_1(::google::protobuf::int32 value) {
  
  altitude_1_ = value;
  // @@protoc_insertion_point(field_set:open_vario.AltitudeNotification.altitude_1)
}

// sint32 altitude_2 = 3;
inline void AltitudeNotification::clear_altitude_2() {
  altitude_2_ = 0;
}
inline ::google::protobuf::int32 AltitudeNotification::altitude_2() const {
  // @@protoc_insertion_point(field_get:open_vario.AltitudeNotification.altitude_2)
  return altitude_2_;
}
inline void AltitudeNotification::set_altitude_2(::google::protobuf::int32 value) {
  
  altitude_2_ = value;
  // @@protoc_insertion_point(field_set:open_vario.AltitudeNotification.altitude_2)
}

// sint32 altitude_3 = 4;
inline void AltitudeNotification::clear_altitude_3() {
  altitude_3_ = 0;
}
inline ::google::protobuf::int32 AltitudeNotification::altitude_3() const {
  // @@protoc_insertion_point(field_get:open_vario.AltitudeNotification.altitude_3)
  return altitude_3_;
}
inline void AltitudeNotification::set_altitude_3(::google::protobuf::int32 value) {
  
  altitude_3_ = value;
  // @@protoc_insertion_point(field_set:open_vario.AltitudeNotification.altitude_3)
}

// sint32 altitude_4 = 5;
inline void AltitudeNotification::clear_altitude_4() {
  altitude_4_ = 0;
}
inline ::google::protobuf::int32 AltitudeNotification::altitude_4() const {
  // @@protoc_insertion_point(field_get:open_vario.AltitudeNotification.altitude_4)
  return altitude_4_;
}
inline void AltitudeNotification::set_altitude_4(::google::protobuf::int32 value) {
  
  altitude_4_ = value;
  // @@protoc_insertion_point(field_set:open_vario.AltitudeNotification.altitude_4)
}

// sint32 min_altitude = 6;
inline void AltitudeNotification::clear_min_altitude() {
  min_altitude_ = 0;
}
inline ::google::protobuf::int32 AltitudeNotification::min_altitude() const {
  // @@protoc_insertion_point(field_get:open_vario.AltitudeNotification.min_altitude)
  return min_altitude_;
}
inline void AltitudeNotification::set_min_altitude(::google::protobuf::int32 value) {
  
  min_altitude_ = value;
  // @@protoc_insertion_point(field_set:open_vario.AltitudeNotification.min_altitude)
}

// sint32 max_altitude = 7;
inline void AltitudeNotification::clear_max_altitude() {
  max_altitude_ = 0;
}
inline ::google::protobuf::int32 AltitudeNotification::max_altitude() const {
  // @@protoc_insertion_point(field_get:open_vario.AltitudeNotification.max_altitude)
  return max_altitude_;
}
inline void AltitudeNotification::set_max_altitude(::google::protobuf::int32 value) {
  
  max_altitude_ = value;
  // @@protoc_insertion_point(field_set:open_vario.AltitudeNotification.max_altitude)
}

// -------------------------------------------------------------------

// VarioNotification

// sint32 vario = 1;
inline void VarioNotification::clear_vario() {
  vario_ = 0;
}
inline ::google::protobuf::int32 VarioNotification::vario() const {
  // @@protoc_insertion_point(field_get:open_vario.VarioNotification.vario)
  return vario_;
}
inline void VarioNotification::set_vario(::google::protobuf::int32 value) {
  
  vario_ = value;
  // @@protoc_insertion_point(field_set:open_vario.VarioNotification.vario)
}

// sint32 min_vario = 2;
inline void VarioNotification::clear_min_vario() {
  min_vario_ = 0;
}
inline ::google::protobuf::int32 VarioNotification::min_vario() const {
  // @@protoc_insertion_point(field_get:open_vario.VarioNotification.min_vario)
  return min_vario_;
}
inline void VarioNotification::set_min_vario(::google::protobuf::int32 value) {
  
  min_vario_ = value;
  // @@protoc_insertion_point(field_set:open_vario.VarioNotification.min_vario)
}

// sint32 max_vario = 3;
inline void VarioNotification::clear_max_vario() {
  max_vario_ = 0;
}
inline ::google::protobuf::int32 VarioNotification::max_vario() const {
  // @@protoc_insertion_point(field_get:open_vario.VarioNotification.max_vario)
  return max_vario_;
}
inline void VarioNotification::set_max_vario(::google::protobuf::int32 value) {
  
  max_vario_ = value;
  // @@protoc_insertion_point(field_set:open_vario.VarioNotification.max_vario)
}

// -------------------------------------------------------------------

// NavigationNotification

// sint32 speed = 1;
inline void NavigationNotification::clear_speed() {
  speed_ = 0;
}
inline ::google::protobuf::int32 NavigationNotification::speed() const {
  // @@protoc_insertion_point(field_get:open_vario.NavigationNotification.speed)
  return speed_;
}
inline void NavigationNotification::set_speed(::google::protobuf::int32 value) {
  
  speed_ = value;
  // @@protoc_insertion_point(field_set:open_vario.NavigationNotification.speed)
}

// double latitude = 2;
inline void NavigationNotification::clear_latitude() {
  latitude_ = 0;
}
inline double NavigationNotification::latitude() const {
  // @@protoc_insertion_point(field_get:open_vario.NavigationNotification.latitude)
  return latitude_;
}
inline void NavigationNotification::set_latitude(double value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:open_vario.NavigationNotification.latitude)
}

// double longitude = 3;
inline void NavigationNotification::clear_longitude() {
  longitude_ = 0;
}
inline double NavigationNotification::longitude() const {
  // @@protoc_insertion_point(field_get:open_vario.NavigationNotification.longitude)
  return longitude_;
}
inline void NavigationNotification::set_longitude(double value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:open_vario.NavigationNotification.longitude)
}

// uint32 track_angle = 4;
inline void NavigationNotification::clear_track_angle() {
  track_angle_ = 0u;
}
inline ::google::protobuf::uint32 NavigationNotification::track_angle() const {
  // @@protoc_insertion_point(field_get:open_vario.NavigationNotification.track_angle)
  return track_angle_;
}
inline void NavigationNotification::set_track_angle(::google::protobuf::uint32 value) {
  
  track_angle_ = value;
  // @@protoc_insertion_point(field_set:open_vario.NavigationNotification.track_angle)
}

// sint32 min_speed = 5;
inline void NavigationNotification::clear_min_speed() {
  min_speed_ = 0;
}
inline ::google::protobuf::int32 NavigationNotification::min_speed() const {
  // @@protoc_insertion_point(field_get:open_vario.NavigationNotification.min_speed)
  return min_speed_;
}
inline void NavigationNotification::set_min_speed(::google::protobuf::int32 value) {
  
  min_speed_ = value;
  // @@protoc_insertion_point(field_set:open_vario.NavigationNotification.min_speed)
}

// sint32 max_speed = 6;
inline void NavigationNotification::clear_max_speed() {
  max_speed_ = 0;
}
inline ::google::protobuf::int32 NavigationNotification::max_speed() const {
  // @@protoc_insertion_point(field_get:open_vario.NavigationNotification.max_speed)
  return max_speed_;
}
inline void NavigationNotification::set_max_speed(::google::protobuf::int32 value) {
  
  max_speed_ = value;
  // @@protoc_insertion_point(field_set:open_vario.NavigationNotification.max_speed)
}

// -------------------------------------------------------------------

// SimuNotification

// .open_vario.PressureNotification pressure = 1;
inline bool SimuNotification::has_pressure() const {
  return Notifications_case() == kPressure;
}
inline void SimuNotification::set_has_pressure() {
  _oneof_case_[0] = kPressure;
}
inline void SimuNotification::clear_pressure() {
  if (has_pressure()) {
    delete Notifications_.pressure_;
    clear_has_Notifications();
  }
}
inline const ::open_vario::PressureNotification& SimuNotification::_internal_pressure() const {
  return *Notifications_.pressure_;
}
inline ::open_vario::PressureNotification* SimuNotification::release_pressure() {
  // @@protoc_insertion_point(field_release:open_vario.SimuNotification.pressure)
  if (has_pressure()) {
    clear_has_Notifications();
      ::open_vario::PressureNotification* temp = Notifications_.pressure_;
    Notifications_.pressure_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::PressureNotification& SimuNotification::pressure() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuNotification.pressure)
  return has_pressure()
      ? *Notifications_.pressure_
      : *reinterpret_cast< ::open_vario::PressureNotification*>(&::open_vario::_PressureNotification_default_instance_);
}
inline ::open_vario::PressureNotification* SimuNotification::mutable_pressure() {
  if (!has_pressure()) {
    clear_Notifications();
    set_has_pressure();
    Notifications_.pressure_ = CreateMaybeMessage< ::open_vario::PressureNotification >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuNotification.pressure)
  return Notifications_.pressure_;
}

// .open_vario.TemperatureNotification temperature = 2;
inline bool SimuNotification::has_temperature() const {
  return Notifications_case() == kTemperature;
}
inline void SimuNotification::set_has_temperature() {
  _oneof_case_[0] = kTemperature;
}
inline void SimuNotification::clear_temperature() {
  if (has_temperature()) {
    delete Notifications_.temperature_;
    clear_has_Notifications();
  }
}
inline const ::open_vario::TemperatureNotification& SimuNotification::_internal_temperature() const {
  return *Notifications_.temperature_;
}
inline ::open_vario::TemperatureNotification* SimuNotification::release_temperature() {
  // @@protoc_insertion_point(field_release:open_vario.SimuNotification.temperature)
  if (has_temperature()) {
    clear_has_Notifications();
      ::open_vario::TemperatureNotification* temp = Notifications_.temperature_;
    Notifications_.temperature_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::TemperatureNotification& SimuNotification::temperature() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuNotification.temperature)
  return has_temperature()
      ? *Notifications_.temperature_
      : *reinterpret_cast< ::open_vario::TemperatureNotification*>(&::open_vario::_TemperatureNotification_default_instance_);
}
inline ::open_vario::TemperatureNotification* SimuNotification::mutable_temperature() {
  if (!has_temperature()) {
    clear_Notifications();
    set_has_temperature();
    Notifications_.temperature_ = CreateMaybeMessage< ::open_vario::TemperatureNotification >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuNotification.temperature)
  return Notifications_.temperature_;
}

// .open_vario.AltitudeNotification altitude = 3;
inline bool SimuNotification::has_altitude() const {
  return Notifications_case() == kAltitude;
}
inline void SimuNotification::set_has_altitude() {
  _oneof_case_[0] = kAltitude;
}
inline void SimuNotification::clear_altitude() {
  if (has_altitude()) {
    delete Notifications_.altitude_;
    clear_has_Notifications();
  }
}
inline const ::open_vario::AltitudeNotification& SimuNotification::_internal_altitude() const {
  return *Notifications_.altitude_;
}
inline ::open_vario::AltitudeNotification* SimuNotification::release_altitude() {
  // @@protoc_insertion_point(field_release:open_vario.SimuNotification.altitude)
  if (has_altitude()) {
    clear_has_Notifications();
      ::open_vario::AltitudeNotification* temp = Notifications_.altitude_;
    Notifications_.altitude_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::AltitudeNotification& SimuNotification::altitude() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuNotification.altitude)
  return has_altitude()
      ? *Notifications_.altitude_
      : *reinterpret_cast< ::open_vario::AltitudeNotification*>(&::open_vario::_AltitudeNotification_default_instance_);
}
inline ::open_vario::AltitudeNotification* SimuNotification::mutable_altitude() {
  if (!has_altitude()) {
    clear_Notifications();
    set_has_altitude();
    Notifications_.altitude_ = CreateMaybeMessage< ::open_vario::AltitudeNotification >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuNotification.altitude)
  return Notifications_.altitude_;
}

// .open_vario.VarioNotification vario = 4;
inline bool SimuNotification::has_vario() const {
  return Notifications_case() == kVario;
}
inline void SimuNotification::set_has_vario() {
  _oneof_case_[0] = kVario;
}
inline void SimuNotification::clear_vario() {
  if (has_vario()) {
    delete Notifications_.vario_;
    clear_has_Notifications();
  }
}
inline const ::open_vario::VarioNotification& SimuNotification::_internal_vario() const {
  return *Notifications_.vario_;
}
inline ::open_vario::VarioNotification* SimuNotification::release_vario() {
  // @@protoc_insertion_point(field_release:open_vario.SimuNotification.vario)
  if (has_vario()) {
    clear_has_Notifications();
      ::open_vario::VarioNotification* temp = Notifications_.vario_;
    Notifications_.vario_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::VarioNotification& SimuNotification::vario() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuNotification.vario)
  return has_vario()
      ? *Notifications_.vario_
      : *reinterpret_cast< ::open_vario::VarioNotification*>(&::open_vario::_VarioNotification_default_instance_);
}
inline ::open_vario::VarioNotification* SimuNotification::mutable_vario() {
  if (!has_vario()) {
    clear_Notifications();
    set_has_vario();
    Notifications_.vario_ = CreateMaybeMessage< ::open_vario::VarioNotification >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuNotification.vario)
  return Notifications_.vario_;
}

// .open_vario.NavigationNotification navigation = 5;
inline bool SimuNotification::has_navigation() const {
  return Notifications_case() == kNavigation;
}
inline void SimuNotification::set_has_navigation() {
  _oneof_case_[0] = kNavigation;
}
inline void SimuNotification::clear_navigation() {
  if (has_navigation()) {
    delete Notifications_.navigation_;
    clear_has_Notifications();
  }
}
inline const ::open_vario::NavigationNotification& SimuNotification::_internal_navigation() const {
  return *Notifications_.navigation_;
}
inline ::open_vario::NavigationNotification* SimuNotification::release_navigation() {
  // @@protoc_insertion_point(field_release:open_vario.SimuNotification.navigation)
  if (has_navigation()) {
    clear_has_Notifications();
      ::open_vario::NavigationNotification* temp = Notifications_.navigation_;
    Notifications_.navigation_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::NavigationNotification& SimuNotification::navigation() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuNotification.navigation)
  return has_navigation()
      ? *Notifications_.navigation_
      : *reinterpret_cast< ::open_vario::NavigationNotification*>(&::open_vario::_NavigationNotification_default_instance_);
}
inline ::open_vario::NavigationNotification* SimuNotification::mutable_navigation() {
  if (!has_navigation()) {
    clear_Notifications();
    set_has_navigation();
    Notifications_.navigation_ = CreateMaybeMessage< ::open_vario::NavigationNotification >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuNotification.navigation)
  return Notifications_.navigation_;
}

inline bool SimuNotification::has_Notifications() const {
  return Notifications_case() != NOTIFICATIONS_NOT_SET;
}
inline void SimuNotification::clear_has_Notifications() {
  _oneof_case_[0] = NOTIFICATIONS_NOT_SET;
}
inline SimuNotification::NotificationsCase SimuNotification::Notifications_case() const {
  return SimuNotification::NotificationsCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace open_vario

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_notifications_2eproto
