// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notifications.proto

#include "notifications.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_notifications_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_notifications_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_AltitudeNotification;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_notifications_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_NavigationNotification;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_notifications_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PressureNotification;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_notifications_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_TemperatureNotification;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_notifications_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_VarioNotification;
}  // namespace protobuf_notifications_2eproto
namespace open_vario {
class StartNotificationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StartNotification>
      _instance;
} _StartNotification_default_instance_;
class PressureNotificationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PressureNotification>
      _instance;
} _PressureNotification_default_instance_;
class TemperatureNotificationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TemperatureNotification>
      _instance;
} _TemperatureNotification_default_instance_;
class AltitudeNotificationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AltitudeNotification>
      _instance;
} _AltitudeNotification_default_instance_;
class VarioNotificationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VarioNotification>
      _instance;
} _VarioNotification_default_instance_;
class NavigationNotificationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NavigationNotification>
      _instance;
} _NavigationNotification_default_instance_;
class SimuNotificationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SimuNotification>
      _instance;
  const ::open_vario::PressureNotification* pressure_;
  const ::open_vario::TemperatureNotification* temperature_;
  const ::open_vario::AltitudeNotification* altitude_;
  const ::open_vario::VarioNotification* vario_;
  const ::open_vario::NavigationNotification* navigation_;
} _SimuNotification_default_instance_;
}  // namespace open_vario
namespace protobuf_notifications_2eproto {
static void InitDefaultsStartNotification() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_StartNotification_default_instance_;
    new (ptr) ::open_vario::StartNotification();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::StartNotification::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_StartNotification =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsStartNotification}, {}};

static void InitDefaultsPressureNotification() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_PressureNotification_default_instance_;
    new (ptr) ::open_vario::PressureNotification();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::PressureNotification::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PressureNotification =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPressureNotification}, {}};

static void InitDefaultsTemperatureNotification() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_TemperatureNotification_default_instance_;
    new (ptr) ::open_vario::TemperatureNotification();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::TemperatureNotification::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_TemperatureNotification =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsTemperatureNotification}, {}};

static void InitDefaultsAltitudeNotification() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_AltitudeNotification_default_instance_;
    new (ptr) ::open_vario::AltitudeNotification();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::AltitudeNotification::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_AltitudeNotification =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsAltitudeNotification}, {}};

static void InitDefaultsVarioNotification() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_VarioNotification_default_instance_;
    new (ptr) ::open_vario::VarioNotification();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::VarioNotification::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_VarioNotification =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsVarioNotification}, {}};

static void InitDefaultsNavigationNotification() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_NavigationNotification_default_instance_;
    new (ptr) ::open_vario::NavigationNotification();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::NavigationNotification::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NavigationNotification =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNavigationNotification}, {}};

static void InitDefaultsSimuNotification() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_SimuNotification_default_instance_;
    new (ptr) ::open_vario::SimuNotification();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::SimuNotification::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<5> scc_info_SimuNotification =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 5, InitDefaultsSimuNotification}, {
      &protobuf_notifications_2eproto::scc_info_PressureNotification.base,
      &protobuf_notifications_2eproto::scc_info_TemperatureNotification.base,
      &protobuf_notifications_2eproto::scc_info_AltitudeNotification.base,
      &protobuf_notifications_2eproto::scc_info_VarioNotification.base,
      &protobuf_notifications_2eproto::scc_info_NavigationNotification.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_StartNotification.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PressureNotification.base);
  ::google::protobuf::internal::InitSCC(&scc_info_TemperatureNotification.base);
  ::google::protobuf::internal::InitSCC(&scc_info_AltitudeNotification.base);
  ::google::protobuf::internal::InitSCC(&scc_info_VarioNotification.base);
  ::google::protobuf::internal::InitSCC(&scc_info_NavigationNotification.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SimuNotification.base);
}

}  // namespace protobuf_notifications_2eproto
namespace open_vario {

// ===================================================================

void StartNotification::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StartNotification::StartNotification()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_notifications_2eproto::scc_info_StartNotification.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.StartNotification)
}
StartNotification::StartNotification(const StartNotification& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:open_vario.StartNotification)
}

void StartNotification::SharedCtor() {
}

StartNotification::~StartNotification() {
  // @@protoc_insertion_point(destructor:open_vario.StartNotification)
  SharedDtor();
}

void StartNotification::SharedDtor() {
}

void StartNotification::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const StartNotification& StartNotification::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_notifications_2eproto::scc_info_StartNotification.base);
  return *internal_default_instance();
}


void StartNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.StartNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool StartNotification::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:open_vario.StartNotification)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(
        input, tag, &unknown_fields_stream));
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.StartNotification)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.StartNotification)
  return false;
#undef DO_
}

void StartNotification::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.StartNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:open_vario.StartNotification)
}

size_t StartNotification::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.StartNotification)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StartNotification::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const StartNotification*>(&from));
}

void StartNotification::MergeFrom(const StartNotification& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.StartNotification)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void StartNotification::CopyFrom(const StartNotification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.StartNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StartNotification::IsInitialized() const {
  return true;
}

void StartNotification::Swap(StartNotification* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StartNotification::InternalSwap(StartNotification* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string StartNotification::GetTypeName() const {
  return "open_vario.StartNotification";
}


// ===================================================================

void PressureNotification::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PressureNotification::kPressureFieldNumber;
const int PressureNotification::kMinPressureFieldNumber;
const int PressureNotification::kMaxPressureFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PressureNotification::PressureNotification()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_notifications_2eproto::scc_info_PressureNotification.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.PressureNotification)
}
PressureNotification::PressureNotification(const PressureNotification& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&pressure_, &from.pressure_,
    static_cast<size_t>(reinterpret_cast<char*>(&max_pressure_) -
    reinterpret_cast<char*>(&pressure_)) + sizeof(max_pressure_));
  // @@protoc_insertion_point(copy_constructor:open_vario.PressureNotification)
}

void PressureNotification::SharedCtor() {
  ::memset(&pressure_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&max_pressure_) -
      reinterpret_cast<char*>(&pressure_)) + sizeof(max_pressure_));
}

PressureNotification::~PressureNotification() {
  // @@protoc_insertion_point(destructor:open_vario.PressureNotification)
  SharedDtor();
}

void PressureNotification::SharedDtor() {
}

void PressureNotification::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PressureNotification& PressureNotification::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_notifications_2eproto::scc_info_PressureNotification.base);
  return *internal_default_instance();
}


void PressureNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.PressureNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&pressure_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&max_pressure_) -
      reinterpret_cast<char*>(&pressure_)) + sizeof(max_pressure_));
  _internal_metadata_.Clear();
}

bool PressureNotification::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:open_vario.PressureNotification)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 pressure = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &pressure_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 min_pressure = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &min_pressure_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 max_pressure = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &max_pressure_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.PressureNotification)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.PressureNotification)
  return false;
#undef DO_
}

void PressureNotification::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.PressureNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 pressure = 1;
  if (this->pressure() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->pressure(), output);
  }

  // uint32 min_pressure = 2;
  if (this->min_pressure() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->min_pressure(), output);
  }

  // uint32 max_pressure = 3;
  if (this->max_pressure() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->max_pressure(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:open_vario.PressureNotification)
}

size_t PressureNotification::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.PressureNotification)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // uint32 pressure = 1;
  if (this->pressure() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->pressure());
  }

  // uint32 min_pressure = 2;
  if (this->min_pressure() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->min_pressure());
  }

  // uint32 max_pressure = 3;
  if (this->max_pressure() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->max_pressure());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PressureNotification::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PressureNotification*>(&from));
}

void PressureNotification::MergeFrom(const PressureNotification& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.PressureNotification)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.pressure() != 0) {
    set_pressure(from.pressure());
  }
  if (from.min_pressure() != 0) {
    set_min_pressure(from.min_pressure());
  }
  if (from.max_pressure() != 0) {
    set_max_pressure(from.max_pressure());
  }
}

void PressureNotification::CopyFrom(const PressureNotification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.PressureNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PressureNotification::IsInitialized() const {
  return true;
}

void PressureNotification::Swap(PressureNotification* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PressureNotification::InternalSwap(PressureNotification* other) {
  using std::swap;
  swap(pressure_, other->pressure_);
  swap(min_pressure_, other->min_pressure_);
  swap(max_pressure_, other->max_pressure_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string PressureNotification::GetTypeName() const {
  return "open_vario.PressureNotification";
}


// ===================================================================

void TemperatureNotification::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TemperatureNotification::kTemperatureFieldNumber;
const int TemperatureNotification::kMinTemperatureFieldNumber;
const int TemperatureNotification::kMaxTemperatureFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TemperatureNotification::TemperatureNotification()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_notifications_2eproto::scc_info_TemperatureNotification.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.TemperatureNotification)
}
TemperatureNotification::TemperatureNotification(const TemperatureNotification& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&temperature_, &from.temperature_,
    static_cast<size_t>(reinterpret_cast<char*>(&max_temperature_) -
    reinterpret_cast<char*>(&temperature_)) + sizeof(max_temperature_));
  // @@protoc_insertion_point(copy_constructor:open_vario.TemperatureNotification)
}

void TemperatureNotification::SharedCtor() {
  ::memset(&temperature_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&max_temperature_) -
      reinterpret_cast<char*>(&temperature_)) + sizeof(max_temperature_));
}

TemperatureNotification::~TemperatureNotification() {
  // @@protoc_insertion_point(destructor:open_vario.TemperatureNotification)
  SharedDtor();
}

void TemperatureNotification::SharedDtor() {
}

void TemperatureNotification::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TemperatureNotification& TemperatureNotification::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_notifications_2eproto::scc_info_TemperatureNotification.base);
  return *internal_default_instance();
}


void TemperatureNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.TemperatureNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&temperature_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&max_temperature_) -
      reinterpret_cast<char*>(&temperature_)) + sizeof(max_temperature_));
  _internal_metadata_.Clear();
}

bool TemperatureNotification::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:open_vario.TemperatureNotification)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // sint32 temperature = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &temperature_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 min_temperature = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &min_temperature_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 max_temperature = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &max_temperature_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.TemperatureNotification)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.TemperatureNotification)
  return false;
#undef DO_
}

void TemperatureNotification::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.TemperatureNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // sint32 temperature = 1;
  if (this->temperature() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(1, this->temperature(), output);
  }

  // sint32 min_temperature = 2;
  if (this->min_temperature() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(2, this->min_temperature(), output);
  }

  // sint32 max_temperature = 3;
  if (this->max_temperature() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(3, this->max_temperature(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:open_vario.TemperatureNotification)
}

size_t TemperatureNotification::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.TemperatureNotification)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // sint32 temperature = 1;
  if (this->temperature() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->temperature());
  }

  // sint32 min_temperature = 2;
  if (this->min_temperature() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->min_temperature());
  }

  // sint32 max_temperature = 3;
  if (this->max_temperature() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->max_temperature());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TemperatureNotification::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const TemperatureNotification*>(&from));
}

void TemperatureNotification::MergeFrom(const TemperatureNotification& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.TemperatureNotification)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.temperature() != 0) {
    set_temperature(from.temperature());
  }
  if (from.min_temperature() != 0) {
    set_min_temperature(from.min_temperature());
  }
  if (from.max_temperature() != 0) {
    set_max_temperature(from.max_temperature());
  }
}

void TemperatureNotification::CopyFrom(const TemperatureNotification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.TemperatureNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TemperatureNotification::IsInitialized() const {
  return true;
}

void TemperatureNotification::Swap(TemperatureNotification* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TemperatureNotification::InternalSwap(TemperatureNotification* other) {
  using std::swap;
  swap(temperature_, other->temperature_);
  swap(min_temperature_, other->min_temperature_);
  swap(max_temperature_, other->max_temperature_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string TemperatureNotification::GetTypeName() const {
  return "open_vario.TemperatureNotification";
}


// ===================================================================

void AltitudeNotification::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AltitudeNotification::kMainAltitudeFieldNumber;
const int AltitudeNotification::kAltitude1FieldNumber;
const int AltitudeNotification::kAltitude2FieldNumber;
const int AltitudeNotification::kAltitude3FieldNumber;
const int AltitudeNotification::kAltitude4FieldNumber;
const int AltitudeNotification::kMinAltitudeFieldNumber;
const int AltitudeNotification::kMaxAltitudeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AltitudeNotification::AltitudeNotification()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_notifications_2eproto::scc_info_AltitudeNotification.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.AltitudeNotification)
}
AltitudeNotification::AltitudeNotification(const AltitudeNotification& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&main_altitude_, &from.main_altitude_,
    static_cast<size_t>(reinterpret_cast<char*>(&max_altitude_) -
    reinterpret_cast<char*>(&main_altitude_)) + sizeof(max_altitude_));
  // @@protoc_insertion_point(copy_constructor:open_vario.AltitudeNotification)
}

void AltitudeNotification::SharedCtor() {
  ::memset(&main_altitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&max_altitude_) -
      reinterpret_cast<char*>(&main_altitude_)) + sizeof(max_altitude_));
}

AltitudeNotification::~AltitudeNotification() {
  // @@protoc_insertion_point(destructor:open_vario.AltitudeNotification)
  SharedDtor();
}

void AltitudeNotification::SharedDtor() {
}

void AltitudeNotification::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AltitudeNotification& AltitudeNotification::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_notifications_2eproto::scc_info_AltitudeNotification.base);
  return *internal_default_instance();
}


void AltitudeNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.AltitudeNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&main_altitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&max_altitude_) -
      reinterpret_cast<char*>(&main_altitude_)) + sizeof(max_altitude_));
  _internal_metadata_.Clear();
}

bool AltitudeNotification::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:open_vario.AltitudeNotification)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // sint32 main_altitude = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &main_altitude_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 altitude_1 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &altitude_1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 altitude_2 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &altitude_2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 altitude_3 = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &altitude_3_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 altitude_4 = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &altitude_4_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 min_altitude = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &min_altitude_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 max_altitude = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &max_altitude_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.AltitudeNotification)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.AltitudeNotification)
  return false;
#undef DO_
}

void AltitudeNotification::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.AltitudeNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // sint32 main_altitude = 1;
  if (this->main_altitude() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(1, this->main_altitude(), output);
  }

  // sint32 altitude_1 = 2;
  if (this->altitude_1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(2, this->altitude_1(), output);
  }

  // sint32 altitude_2 = 3;
  if (this->altitude_2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(3, this->altitude_2(), output);
  }

  // sint32 altitude_3 = 4;
  if (this->altitude_3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(4, this->altitude_3(), output);
  }

  // sint32 altitude_4 = 5;
  if (this->altitude_4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(5, this->altitude_4(), output);
  }

  // sint32 min_altitude = 6;
  if (this->min_altitude() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(6, this->min_altitude(), output);
  }

  // sint32 max_altitude = 7;
  if (this->max_altitude() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(7, this->max_altitude(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:open_vario.AltitudeNotification)
}

size_t AltitudeNotification::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.AltitudeNotification)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // sint32 main_altitude = 1;
  if (this->main_altitude() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->main_altitude());
  }

  // sint32 altitude_1 = 2;
  if (this->altitude_1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->altitude_1());
  }

  // sint32 altitude_2 = 3;
  if (this->altitude_2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->altitude_2());
  }

  // sint32 altitude_3 = 4;
  if (this->altitude_3() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->altitude_3());
  }

  // sint32 altitude_4 = 5;
  if (this->altitude_4() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->altitude_4());
  }

  // sint32 min_altitude = 6;
  if (this->min_altitude() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->min_altitude());
  }

  // sint32 max_altitude = 7;
  if (this->max_altitude() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->max_altitude());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AltitudeNotification::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const AltitudeNotification*>(&from));
}

void AltitudeNotification::MergeFrom(const AltitudeNotification& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.AltitudeNotification)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.main_altitude() != 0) {
    set_main_altitude(from.main_altitude());
  }
  if (from.altitude_1() != 0) {
    set_altitude_1(from.altitude_1());
  }
  if (from.altitude_2() != 0) {
    set_altitude_2(from.altitude_2());
  }
  if (from.altitude_3() != 0) {
    set_altitude_3(from.altitude_3());
  }
  if (from.altitude_4() != 0) {
    set_altitude_4(from.altitude_4());
  }
  if (from.min_altitude() != 0) {
    set_min_altitude(from.min_altitude());
  }
  if (from.max_altitude() != 0) {
    set_max_altitude(from.max_altitude());
  }
}

void AltitudeNotification::CopyFrom(const AltitudeNotification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.AltitudeNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AltitudeNotification::IsInitialized() const {
  return true;
}

void AltitudeNotification::Swap(AltitudeNotification* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AltitudeNotification::InternalSwap(AltitudeNotification* other) {
  using std::swap;
  swap(main_altitude_, other->main_altitude_);
  swap(altitude_1_, other->altitude_1_);
  swap(altitude_2_, other->altitude_2_);
  swap(altitude_3_, other->altitude_3_);
  swap(altitude_4_, other->altitude_4_);
  swap(min_altitude_, other->min_altitude_);
  swap(max_altitude_, other->max_altitude_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string AltitudeNotification::GetTypeName() const {
  return "open_vario.AltitudeNotification";
}


// ===================================================================

void VarioNotification::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VarioNotification::kVarioFieldNumber;
const int VarioNotification::kMinVarioFieldNumber;
const int VarioNotification::kMaxVarioFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VarioNotification::VarioNotification()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_notifications_2eproto::scc_info_VarioNotification.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.VarioNotification)
}
VarioNotification::VarioNotification(const VarioNotification& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&vario_, &from.vario_,
    static_cast<size_t>(reinterpret_cast<char*>(&max_vario_) -
    reinterpret_cast<char*>(&vario_)) + sizeof(max_vario_));
  // @@protoc_insertion_point(copy_constructor:open_vario.VarioNotification)
}

void VarioNotification::SharedCtor() {
  ::memset(&vario_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&max_vario_) -
      reinterpret_cast<char*>(&vario_)) + sizeof(max_vario_));
}

VarioNotification::~VarioNotification() {
  // @@protoc_insertion_point(destructor:open_vario.VarioNotification)
  SharedDtor();
}

void VarioNotification::SharedDtor() {
}

void VarioNotification::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const VarioNotification& VarioNotification::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_notifications_2eproto::scc_info_VarioNotification.base);
  return *internal_default_instance();
}


void VarioNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.VarioNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&vario_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&max_vario_) -
      reinterpret_cast<char*>(&vario_)) + sizeof(max_vario_));
  _internal_metadata_.Clear();
}

bool VarioNotification::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:open_vario.VarioNotification)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // sint32 vario = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &vario_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 min_vario = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &min_vario_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 max_vario = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &max_vario_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.VarioNotification)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.VarioNotification)
  return false;
#undef DO_
}

void VarioNotification::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.VarioNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // sint32 vario = 1;
  if (this->vario() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(1, this->vario(), output);
  }

  // sint32 min_vario = 2;
  if (this->min_vario() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(2, this->min_vario(), output);
  }

  // sint32 max_vario = 3;
  if (this->max_vario() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(3, this->max_vario(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:open_vario.VarioNotification)
}

size_t VarioNotification::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.VarioNotification)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // sint32 vario = 1;
  if (this->vario() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->vario());
  }

  // sint32 min_vario = 2;
  if (this->min_vario() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->min_vario());
  }

  // sint32 max_vario = 3;
  if (this->max_vario() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->max_vario());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VarioNotification::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const VarioNotification*>(&from));
}

void VarioNotification::MergeFrom(const VarioNotification& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.VarioNotification)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.vario() != 0) {
    set_vario(from.vario());
  }
  if (from.min_vario() != 0) {
    set_min_vario(from.min_vario());
  }
  if (from.max_vario() != 0) {
    set_max_vario(from.max_vario());
  }
}

void VarioNotification::CopyFrom(const VarioNotification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.VarioNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VarioNotification::IsInitialized() const {
  return true;
}

void VarioNotification::Swap(VarioNotification* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VarioNotification::InternalSwap(VarioNotification* other) {
  using std::swap;
  swap(vario_, other->vario_);
  swap(min_vario_, other->min_vario_);
  swap(max_vario_, other->max_vario_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string VarioNotification::GetTypeName() const {
  return "open_vario.VarioNotification";
}


// ===================================================================

void NavigationNotification::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NavigationNotification::kSpeedFieldNumber;
const int NavigationNotification::kLatitudeFieldNumber;
const int NavigationNotification::kLongitudeFieldNumber;
const int NavigationNotification::kTrackAngleFieldNumber;
const int NavigationNotification::kMinSpeedFieldNumber;
const int NavigationNotification::kMaxSpeedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NavigationNotification::NavigationNotification()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_notifications_2eproto::scc_info_NavigationNotification.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.NavigationNotification)
}
NavigationNotification::NavigationNotification(const NavigationNotification& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&latitude_, &from.latitude_,
    static_cast<size_t>(reinterpret_cast<char*>(&max_speed_) -
    reinterpret_cast<char*>(&latitude_)) + sizeof(max_speed_));
  // @@protoc_insertion_point(copy_constructor:open_vario.NavigationNotification)
}

void NavigationNotification::SharedCtor() {
  ::memset(&latitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&max_speed_) -
      reinterpret_cast<char*>(&latitude_)) + sizeof(max_speed_));
}

NavigationNotification::~NavigationNotification() {
  // @@protoc_insertion_point(destructor:open_vario.NavigationNotification)
  SharedDtor();
}

void NavigationNotification::SharedDtor() {
}

void NavigationNotification::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NavigationNotification& NavigationNotification::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_notifications_2eproto::scc_info_NavigationNotification.base);
  return *internal_default_instance();
}


void NavigationNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.NavigationNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&latitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&max_speed_) -
      reinterpret_cast<char*>(&latitude_)) + sizeof(max_speed_));
  _internal_metadata_.Clear();
}

bool NavigationNotification::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:open_vario.NavigationNotification)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // sint32 speed = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &speed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double latitude = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &latitude_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double longitude = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &longitude_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 track_angle = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &track_angle_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 min_speed = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &min_speed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 max_speed = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &max_speed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.NavigationNotification)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.NavigationNotification)
  return false;
#undef DO_
}

void NavigationNotification::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.NavigationNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // sint32 speed = 1;
  if (this->speed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(1, this->speed(), output);
  }

  // double latitude = 2;
  if (this->latitude() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->latitude(), output);
  }

  // double longitude = 3;
  if (this->longitude() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->longitude(), output);
  }

  // uint32 track_angle = 4;
  if (this->track_angle() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->track_angle(), output);
  }

  // sint32 min_speed = 5;
  if (this->min_speed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(5, this->min_speed(), output);
  }

  // sint32 max_speed = 6;
  if (this->max_speed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(6, this->max_speed(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:open_vario.NavigationNotification)
}

size_t NavigationNotification::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.NavigationNotification)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // double latitude = 2;
  if (this->latitude() != 0) {
    total_size += 1 + 8;
  }

  // sint32 speed = 1;
  if (this->speed() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->speed());
  }

  // uint32 track_angle = 4;
  if (this->track_angle() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->track_angle());
  }

  // double longitude = 3;
  if (this->longitude() != 0) {
    total_size += 1 + 8;
  }

  // sint32 min_speed = 5;
  if (this->min_speed() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->min_speed());
  }

  // sint32 max_speed = 6;
  if (this->max_speed() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->max_speed());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NavigationNotification::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const NavigationNotification*>(&from));
}

void NavigationNotification::MergeFrom(const NavigationNotification& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.NavigationNotification)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.latitude() != 0) {
    set_latitude(from.latitude());
  }
  if (from.speed() != 0) {
    set_speed(from.speed());
  }
  if (from.track_angle() != 0) {
    set_track_angle(from.track_angle());
  }
  if (from.longitude() != 0) {
    set_longitude(from.longitude());
  }
  if (from.min_speed() != 0) {
    set_min_speed(from.min_speed());
  }
  if (from.max_speed() != 0) {
    set_max_speed(from.max_speed());
  }
}

void NavigationNotification::CopyFrom(const NavigationNotification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.NavigationNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NavigationNotification::IsInitialized() const {
  return true;
}

void NavigationNotification::Swap(NavigationNotification* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NavigationNotification::InternalSwap(NavigationNotification* other) {
  using std::swap;
  swap(latitude_, other->latitude_);
  swap(speed_, other->speed_);
  swap(track_angle_, other->track_angle_);
  swap(longitude_, other->longitude_);
  swap(min_speed_, other->min_speed_);
  swap(max_speed_, other->max_speed_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string NavigationNotification::GetTypeName() const {
  return "open_vario.NavigationNotification";
}


// ===================================================================

void SimuNotification::InitAsDefaultInstance() {
}
void SimuNotification::set_allocated_pressure(::open_vario::PressureNotification* pressure) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_Notifications();
  if (pressure) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pressure = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pressure, submessage_arena);
    }
    set_has_pressure();
    Notifications_.pressure_ = pressure;
  }
  // @@protoc_insertion_point(field_set_allocated:open_vario.SimuNotification.pressure)
}
void SimuNotification::set_allocated_temperature(::open_vario::TemperatureNotification* temperature) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_Notifications();
  if (temperature) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      temperature = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, temperature, submessage_arena);
    }
    set_has_temperature();
    Notifications_.temperature_ = temperature;
  }
  // @@protoc_insertion_point(field_set_allocated:open_vario.SimuNotification.temperature)
}
void SimuNotification::set_allocated_altitude(::open_vario::AltitudeNotification* altitude) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_Notifications();
  if (altitude) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      altitude = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, altitude, submessage_arena);
    }
    set_has_altitude();
    Notifications_.altitude_ = altitude;
  }
  // @@protoc_insertion_point(field_set_allocated:open_vario.SimuNotification.altitude)
}
void SimuNotification::set_allocated_vario(::open_vario::VarioNotification* vario) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_Notifications();
  if (vario) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      vario = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, vario, submessage_arena);
    }
    set_has_vario();
    Notifications_.vario_ = vario;
  }
  // @@protoc_insertion_point(field_set_allocated:open_vario.SimuNotification.vario)
}
void SimuNotification::set_allocated_navigation(::open_vario::NavigationNotification* navigation) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_Notifications();
  if (navigation) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      navigation = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, navigation, submessage_arena);
    }
    set_has_navigation();
    Notifications_.navigation_ = navigation;
  }
  // @@protoc_insertion_point(field_set_allocated:open_vario.SimuNotification.navigation)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SimuNotification::kPressureFieldNumber;
const int SimuNotification::kTemperatureFieldNumber;
const int SimuNotification::kAltitudeFieldNumber;
const int SimuNotification::kVarioFieldNumber;
const int SimuNotification::kNavigationFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SimuNotification::SimuNotification()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_notifications_2eproto::scc_info_SimuNotification.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.SimuNotification)
}
SimuNotification::SimuNotification(const SimuNotification& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_Notifications();
  switch (from.Notifications_case()) {
    case kPressure: {
      mutable_pressure()->::open_vario::PressureNotification::MergeFrom(from.pressure());
      break;
    }
    case kTemperature: {
      mutable_temperature()->::open_vario::TemperatureNotification::MergeFrom(from.temperature());
      break;
    }
    case kAltitude: {
      mutable_altitude()->::open_vario::AltitudeNotification::MergeFrom(from.altitude());
      break;
    }
    case kVario: {
      mutable_vario()->::open_vario::VarioNotification::MergeFrom(from.vario());
      break;
    }
    case kNavigation: {
      mutable_navigation()->::open_vario::NavigationNotification::MergeFrom(from.navigation());
      break;
    }
    case NOTIFICATIONS_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:open_vario.SimuNotification)
}

void SimuNotification::SharedCtor() {
  clear_has_Notifications();
}

SimuNotification::~SimuNotification() {
  // @@protoc_insertion_point(destructor:open_vario.SimuNotification)
  SharedDtor();
}

void SimuNotification::SharedDtor() {
  if (has_Notifications()) {
    clear_Notifications();
  }
}

void SimuNotification::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SimuNotification& SimuNotification::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_notifications_2eproto::scc_info_SimuNotification.base);
  return *internal_default_instance();
}


void SimuNotification::clear_Notifications() {
// @@protoc_insertion_point(one_of_clear_start:open_vario.SimuNotification)
  switch (Notifications_case()) {
    case kPressure: {
      delete Notifications_.pressure_;
      break;
    }
    case kTemperature: {
      delete Notifications_.temperature_;
      break;
    }
    case kAltitude: {
      delete Notifications_.altitude_;
      break;
    }
    case kVario: {
      delete Notifications_.vario_;
      break;
    }
    case kNavigation: {
      delete Notifications_.navigation_;
      break;
    }
    case NOTIFICATIONS_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = NOTIFICATIONS_NOT_SET;
}


void SimuNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.SimuNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_Notifications();
  _internal_metadata_.Clear();
}

bool SimuNotification::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:open_vario.SimuNotification)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .open_vario.PressureNotification pressure = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_pressure()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .open_vario.TemperatureNotification temperature = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_temperature()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .open_vario.AltitudeNotification altitude = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_altitude()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .open_vario.VarioNotification vario = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_vario()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .open_vario.NavigationNotification navigation = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_navigation()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.SimuNotification)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.SimuNotification)
  return false;
#undef DO_
}

void SimuNotification::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.SimuNotification)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .open_vario.PressureNotification pressure = 1;
  if (has_pressure()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->_internal_pressure(), output);
  }

  // .open_vario.TemperatureNotification temperature = 2;
  if (has_temperature()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->_internal_temperature(), output);
  }

  // .open_vario.AltitudeNotification altitude = 3;
  if (has_altitude()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->_internal_altitude(), output);
  }

  // .open_vario.VarioNotification vario = 4;
  if (has_vario()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, this->_internal_vario(), output);
  }

  // .open_vario.NavigationNotification navigation = 5;
  if (has_navigation()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      5, this->_internal_navigation(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:open_vario.SimuNotification)
}

size_t SimuNotification::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.SimuNotification)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  switch (Notifications_case()) {
    // .open_vario.PressureNotification pressure = 1;
    case kPressure: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *Notifications_.pressure_);
      break;
    }
    // .open_vario.TemperatureNotification temperature = 2;
    case kTemperature: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *Notifications_.temperature_);
      break;
    }
    // .open_vario.AltitudeNotification altitude = 3;
    case kAltitude: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *Notifications_.altitude_);
      break;
    }
    // .open_vario.VarioNotification vario = 4;
    case kVario: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *Notifications_.vario_);
      break;
    }
    // .open_vario.NavigationNotification navigation = 5;
    case kNavigation: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *Notifications_.navigation_);
      break;
    }
    case NOTIFICATIONS_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SimuNotification::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const SimuNotification*>(&from));
}

void SimuNotification::MergeFrom(const SimuNotification& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.SimuNotification)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.Notifications_case()) {
    case kPressure: {
      mutable_pressure()->::open_vario::PressureNotification::MergeFrom(from.pressure());
      break;
    }
    case kTemperature: {
      mutable_temperature()->::open_vario::TemperatureNotification::MergeFrom(from.temperature());
      break;
    }
    case kAltitude: {
      mutable_altitude()->::open_vario::AltitudeNotification::MergeFrom(from.altitude());
      break;
    }
    case kVario: {
      mutable_vario()->::open_vario::VarioNotification::MergeFrom(from.vario());
      break;
    }
    case kNavigation: {
      mutable_navigation()->::open_vario::NavigationNotification::MergeFrom(from.navigation());
      break;
    }
    case NOTIFICATIONS_NOT_SET: {
      break;
    }
  }
}

void SimuNotification::CopyFrom(const SimuNotification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.SimuNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimuNotification::IsInitialized() const {
  return true;
}

void SimuNotification::Swap(SimuNotification* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SimuNotification::InternalSwap(SimuNotification* other) {
  using std::swap;
  swap(Notifications_, other->Notifications_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string SimuNotification::GetTypeName() const {
  return "open_vario.SimuNotification";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace open_vario
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::StartNotification* Arena::CreateMaybeMessage< ::open_vario::StartNotification >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::StartNotification >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::PressureNotification* Arena::CreateMaybeMessage< ::open_vario::PressureNotification >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::PressureNotification >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::TemperatureNotification* Arena::CreateMaybeMessage< ::open_vario::TemperatureNotification >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::TemperatureNotification >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::AltitudeNotification* Arena::CreateMaybeMessage< ::open_vario::AltitudeNotification >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::AltitudeNotification >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::VarioNotification* Arena::CreateMaybeMessage< ::open_vario::VarioNotification >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::VarioNotification >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::NavigationNotification* Arena::CreateMaybeMessage< ::open_vario::NavigationNotification >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::NavigationNotification >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::SimuNotification* Arena::CreateMaybeMessage< ::open_vario::SimuNotification >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::SimuNotification >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
