// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests.proto

#ifndef PROTOBUF_INCLUDED_requests_2eproto
#define PROTOBUF_INCLUDED_requests_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_requests_2eproto 

namespace protobuf_requests_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_requests_2eproto
namespace open_vario {
class ConnectRequest;
class ConnectRequestDefaultTypeInternal;
extern ConnectRequestDefaultTypeInternal _ConnectRequest_default_instance_;
class ConnectRequest_NotificationEndpoint;
class ConnectRequest_NotificationEndpointDefaultTypeInternal;
extern ConnectRequest_NotificationEndpointDefaultTypeInternal _ConnectRequest_NotificationEndpoint_default_instance_;
class DisconnectRequest;
class DisconnectRequestDefaultTypeInternal;
extern DisconnectRequestDefaultTypeInternal _DisconnectRequest_default_instance_;
class ListSensorsRequest;
class ListSensorsRequestDefaultTypeInternal;
extern ListSensorsRequestDefaultTypeInternal _ListSensorsRequest_default_instance_;
class PingRequest;
class PingRequestDefaultTypeInternal;
extern PingRequestDefaultTypeInternal _PingRequest_default_instance_;
class SimuRequest;
class SimuRequestDefaultTypeInternal;
extern SimuRequestDefaultTypeInternal _SimuRequest_default_instance_;
class UpdateSensorRequest;
class UpdateSensorRequestDefaultTypeInternal;
extern UpdateSensorRequestDefaultTypeInternal _UpdateSensorRequest_default_instance_;
}  // namespace open_vario
namespace google {
namespace protobuf {
template<> ::open_vario::ConnectRequest* Arena::CreateMaybeMessage<::open_vario::ConnectRequest>(Arena*);
template<> ::open_vario::ConnectRequest_NotificationEndpoint* Arena::CreateMaybeMessage<::open_vario::ConnectRequest_NotificationEndpoint>(Arena*);
template<> ::open_vario::DisconnectRequest* Arena::CreateMaybeMessage<::open_vario::DisconnectRequest>(Arena*);
template<> ::open_vario::ListSensorsRequest* Arena::CreateMaybeMessage<::open_vario::ListSensorsRequest>(Arena*);
template<> ::open_vario::PingRequest* Arena::CreateMaybeMessage<::open_vario::PingRequest>(Arena*);
template<> ::open_vario::SimuRequest* Arena::CreateMaybeMessage<::open_vario::SimuRequest>(Arena*);
template<> ::open_vario::UpdateSensorRequest* Arena::CreateMaybeMessage<::open_vario::UpdateSensorRequest>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace open_vario {

// ===================================================================

class ConnectRequest_NotificationEndpoint : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.ConnectRequest.NotificationEndpoint) */ {
 public:
  ConnectRequest_NotificationEndpoint();
  virtual ~ConnectRequest_NotificationEndpoint();

  ConnectRequest_NotificationEndpoint(const ConnectRequest_NotificationEndpoint& from);

  inline ConnectRequest_NotificationEndpoint& operator=(const ConnectRequest_NotificationEndpoint& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConnectRequest_NotificationEndpoint(ConnectRequest_NotificationEndpoint&& from) noexcept
    : ConnectRequest_NotificationEndpoint() {
    *this = ::std::move(from);
  }

  inline ConnectRequest_NotificationEndpoint& operator=(ConnectRequest_NotificationEndpoint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ConnectRequest_NotificationEndpoint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConnectRequest_NotificationEndpoint* internal_default_instance() {
    return reinterpret_cast<const ConnectRequest_NotificationEndpoint*>(
               &_ConnectRequest_NotificationEndpoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ConnectRequest_NotificationEndpoint* other);
  friend void swap(ConnectRequest_NotificationEndpoint& a, ConnectRequest_NotificationEndpoint& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConnectRequest_NotificationEndpoint* New() const final {
    return CreateMaybeMessage<ConnectRequest_NotificationEndpoint>(NULL);
  }

  ConnectRequest_NotificationEndpoint* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConnectRequest_NotificationEndpoint>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ConnectRequest_NotificationEndpoint& from);
  void MergeFrom(const ConnectRequest_NotificationEndpoint& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ConnectRequest_NotificationEndpoint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string ip_address = 1;
  void clear_ip_address();
  static const int kIpAddressFieldNumber = 1;
  const ::std::string& ip_address() const;
  void set_ip_address(const ::std::string& value);
  #if LANG_CXX11
  void set_ip_address(::std::string&& value);
  #endif
  void set_ip_address(const char* value);
  void set_ip_address(const char* value, size_t size);
  ::std::string* mutable_ip_address();
  ::std::string* release_ip_address();
  void set_allocated_ip_address(::std::string* ip_address);

  // uint32 port = 2;
  void clear_port();
  static const int kPortFieldNumber = 2;
  ::google::protobuf::uint32 port() const;
  void set_port(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:open_vario.ConnectRequest.NotificationEndpoint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr ip_address_;
  ::google::protobuf::uint32 port_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_requests_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ConnectRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.ConnectRequest) */ {
 public:
  ConnectRequest();
  virtual ~ConnectRequest();

  ConnectRequest(const ConnectRequest& from);

  inline ConnectRequest& operator=(const ConnectRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConnectRequest(ConnectRequest&& from) noexcept
    : ConnectRequest() {
    *this = ::std::move(from);
  }

  inline ConnectRequest& operator=(ConnectRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ConnectRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConnectRequest* internal_default_instance() {
    return reinterpret_cast<const ConnectRequest*>(
               &_ConnectRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ConnectRequest* other);
  friend void swap(ConnectRequest& a, ConnectRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConnectRequest* New() const final {
    return CreateMaybeMessage<ConnectRequest>(NULL);
  }

  ConnectRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConnectRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ConnectRequest& from);
  void MergeFrom(const ConnectRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ConnectRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef ConnectRequest_NotificationEndpoint NotificationEndpoint;

  // accessors -------------------------------------------------------

  // .open_vario.ConnectRequest.NotificationEndpoint notification_endpoint = 1;
  bool has_notification_endpoint() const;
  void clear_notification_endpoint();
  static const int kNotificationEndpointFieldNumber = 1;
  private:
  const ::open_vario::ConnectRequest_NotificationEndpoint& _internal_notification_endpoint() const;
  public:
  const ::open_vario::ConnectRequest_NotificationEndpoint& notification_endpoint() const;
  ::open_vario::ConnectRequest_NotificationEndpoint* release_notification_endpoint();
  ::open_vario::ConnectRequest_NotificationEndpoint* mutable_notification_endpoint();
  void set_allocated_notification_endpoint(::open_vario::ConnectRequest_NotificationEndpoint* notification_endpoint);

  // @@protoc_insertion_point(class_scope:open_vario.ConnectRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::open_vario::ConnectRequest_NotificationEndpoint* notification_endpoint_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_requests_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DisconnectRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.DisconnectRequest) */ {
 public:
  DisconnectRequest();
  virtual ~DisconnectRequest();

  DisconnectRequest(const DisconnectRequest& from);

  inline DisconnectRequest& operator=(const DisconnectRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DisconnectRequest(DisconnectRequest&& from) noexcept
    : DisconnectRequest() {
    *this = ::std::move(from);
  }

  inline DisconnectRequest& operator=(DisconnectRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const DisconnectRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DisconnectRequest* internal_default_instance() {
    return reinterpret_cast<const DisconnectRequest*>(
               &_DisconnectRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(DisconnectRequest* other);
  friend void swap(DisconnectRequest& a, DisconnectRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DisconnectRequest* New() const final {
    return CreateMaybeMessage<DisconnectRequest>(NULL);
  }

  DisconnectRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DisconnectRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const DisconnectRequest& from);
  void MergeFrom(const DisconnectRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DisconnectRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:open_vario.DisconnectRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_requests_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ListSensorsRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.ListSensorsRequest) */ {
 public:
  ListSensorsRequest();
  virtual ~ListSensorsRequest();

  ListSensorsRequest(const ListSensorsRequest& from);

  inline ListSensorsRequest& operator=(const ListSensorsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ListSensorsRequest(ListSensorsRequest&& from) noexcept
    : ListSensorsRequest() {
    *this = ::std::move(from);
  }

  inline ListSensorsRequest& operator=(ListSensorsRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ListSensorsRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ListSensorsRequest* internal_default_instance() {
    return reinterpret_cast<const ListSensorsRequest*>(
               &_ListSensorsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ListSensorsRequest* other);
  friend void swap(ListSensorsRequest& a, ListSensorsRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ListSensorsRequest* New() const final {
    return CreateMaybeMessage<ListSensorsRequest>(NULL);
  }

  ListSensorsRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ListSensorsRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ListSensorsRequest& from);
  void MergeFrom(const ListSensorsRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListSensorsRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:open_vario.ListSensorsRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_requests_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UpdateSensorRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.UpdateSensorRequest) */ {
 public:
  UpdateSensorRequest();
  virtual ~UpdateSensorRequest();

  UpdateSensorRequest(const UpdateSensorRequest& from);

  inline UpdateSensorRequest& operator=(const UpdateSensorRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UpdateSensorRequest(UpdateSensorRequest&& from) noexcept
    : UpdateSensorRequest() {
    *this = ::std::move(from);
  }

  inline UpdateSensorRequest& operator=(UpdateSensorRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const UpdateSensorRequest& default_instance();

  enum ValuesCase {
    kUintValue = 2,
    kIntValue = 3,
    kFloatValue = 4,
    kDoubleValue = 5,
    kStringValue = 6,
    kBoolValue = 7,
    VALUES_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateSensorRequest* internal_default_instance() {
    return reinterpret_cast<const UpdateSensorRequest*>(
               &_UpdateSensorRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(UpdateSensorRequest* other);
  friend void swap(UpdateSensorRequest& a, UpdateSensorRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UpdateSensorRequest* New() const final {
    return CreateMaybeMessage<UpdateSensorRequest>(NULL);
  }

  UpdateSensorRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UpdateSensorRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const UpdateSensorRequest& from);
  void MergeFrom(const UpdateSensorRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateSensorRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // uint32 uint_value = 2;
  private:
  bool has_uint_value() const;
  public:
  void clear_uint_value();
  static const int kUintValueFieldNumber = 2;
  ::google::protobuf::uint32 uint_value() const;
  void set_uint_value(::google::protobuf::uint32 value);

  // sint32 int_value = 3;
  private:
  bool has_int_value() const;
  public:
  void clear_int_value();
  static const int kIntValueFieldNumber = 3;
  ::google::protobuf::int32 int_value() const;
  void set_int_value(::google::protobuf::int32 value);

  // float float_value = 4;
  private:
  bool has_float_value() const;
  public:
  void clear_float_value();
  static const int kFloatValueFieldNumber = 4;
  float float_value() const;
  void set_float_value(float value);

  // double double_value = 5;
  private:
  bool has_double_value() const;
  public:
  void clear_double_value();
  static const int kDoubleValueFieldNumber = 5;
  double double_value() const;
  void set_double_value(double value);

  // string string_value = 6;
  private:
  bool has_string_value() const;
  public:
  void clear_string_value();
  static const int kStringValueFieldNumber = 6;
  const ::std::string& string_value() const;
  void set_string_value(const ::std::string& value);
  #if LANG_CXX11
  void set_string_value(::std::string&& value);
  #endif
  void set_string_value(const char* value);
  void set_string_value(const char* value, size_t size);
  ::std::string* mutable_string_value();
  ::std::string* release_string_value();
  void set_allocated_string_value(::std::string* string_value);

  // bool bool_value = 7;
  private:
  bool has_bool_value() const;
  public:
  void clear_bool_value();
  static const int kBoolValueFieldNumber = 7;
  bool bool_value() const;
  void set_bool_value(bool value);

  void clear_Values();
  ValuesCase Values_case() const;
  // @@protoc_insertion_point(class_scope:open_vario.UpdateSensorRequest)
 private:
  void set_has_uint_value();
  void set_has_int_value();
  void set_has_float_value();
  void set_has_double_value();
  void set_has_string_value();
  void set_has_bool_value();

  inline bool has_Values() const;
  inline void clear_has_Values();

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::uint32 id_;
  union ValuesUnion {
    ValuesUnion() {}
    ::google::protobuf::uint32 uint_value_;
    ::google::protobuf::int32 int_value_;
    float float_value_;
    double double_value_;
    ::google::protobuf::internal::ArenaStringPtr string_value_;
    bool bool_value_;
  } Values_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::protobuf_requests_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PingRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.PingRequest) */ {
 public:
  PingRequest();
  virtual ~PingRequest();

  PingRequest(const PingRequest& from);

  inline PingRequest& operator=(const PingRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PingRequest(PingRequest&& from) noexcept
    : PingRequest() {
    *this = ::std::move(from);
  }

  inline PingRequest& operator=(PingRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const PingRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PingRequest* internal_default_instance() {
    return reinterpret_cast<const PingRequest*>(
               &_PingRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(PingRequest* other);
  friend void swap(PingRequest& a, PingRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PingRequest* New() const final {
    return CreateMaybeMessage<PingRequest>(NULL);
  }

  PingRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PingRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const PingRequest& from);
  void MergeFrom(const PingRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PingRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 number = 1;
  void clear_number();
  static const int kNumberFieldNumber = 1;
  ::google::protobuf::uint32 number() const;
  void set_number(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:open_vario.PingRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::uint32 number_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_requests_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SimuRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.SimuRequest) */ {
 public:
  SimuRequest();
  virtual ~SimuRequest();

  SimuRequest(const SimuRequest& from);

  inline SimuRequest& operator=(const SimuRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SimuRequest(SimuRequest&& from) noexcept
    : SimuRequest() {
    *this = ::std::move(from);
  }

  inline SimuRequest& operator=(SimuRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const SimuRequest& default_instance();

  enum RequestsCase {
    kConnect = 1,
    kDisconnect = 2,
    kListSensors = 3,
    kUpdateSensor = 4,
    kPing = 5,
    REQUESTS_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SimuRequest* internal_default_instance() {
    return reinterpret_cast<const SimuRequest*>(
               &_SimuRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(SimuRequest* other);
  friend void swap(SimuRequest& a, SimuRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SimuRequest* New() const final {
    return CreateMaybeMessage<SimuRequest>(NULL);
  }

  SimuRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SimuRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const SimuRequest& from);
  void MergeFrom(const SimuRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SimuRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .open_vario.ConnectRequest connect = 1;
  bool has_connect() const;
  void clear_connect();
  static const int kConnectFieldNumber = 1;
  private:
  const ::open_vario::ConnectRequest& _internal_connect() const;
  public:
  const ::open_vario::ConnectRequest& connect() const;
  ::open_vario::ConnectRequest* release_connect();
  ::open_vario::ConnectRequest* mutable_connect();
  void set_allocated_connect(::open_vario::ConnectRequest* connect);

  // .open_vario.DisconnectRequest disconnect = 2;
  bool has_disconnect() const;
  void clear_disconnect();
  static const int kDisconnectFieldNumber = 2;
  private:
  const ::open_vario::DisconnectRequest& _internal_disconnect() const;
  public:
  const ::open_vario::DisconnectRequest& disconnect() const;
  ::open_vario::DisconnectRequest* release_disconnect();
  ::open_vario::DisconnectRequest* mutable_disconnect();
  void set_allocated_disconnect(::open_vario::DisconnectRequest* disconnect);

  // .open_vario.ListSensorsRequest list_sensors = 3;
  bool has_list_sensors() const;
  void clear_list_sensors();
  static const int kListSensorsFieldNumber = 3;
  private:
  const ::open_vario::ListSensorsRequest& _internal_list_sensors() const;
  public:
  const ::open_vario::ListSensorsRequest& list_sensors() const;
  ::open_vario::ListSensorsRequest* release_list_sensors();
  ::open_vario::ListSensorsRequest* mutable_list_sensors();
  void set_allocated_list_sensors(::open_vario::ListSensorsRequest* list_sensors);

  // .open_vario.UpdateSensorRequest update_sensor = 4;
  bool has_update_sensor() const;
  void clear_update_sensor();
  static const int kUpdateSensorFieldNumber = 4;
  private:
  const ::open_vario::UpdateSensorRequest& _internal_update_sensor() const;
  public:
  const ::open_vario::UpdateSensorRequest& update_sensor() const;
  ::open_vario::UpdateSensorRequest* release_update_sensor();
  ::open_vario::UpdateSensorRequest* mutable_update_sensor();
  void set_allocated_update_sensor(::open_vario::UpdateSensorRequest* update_sensor);

  // .open_vario.PingRequest ping = 5;
  bool has_ping() const;
  void clear_ping();
  static const int kPingFieldNumber = 5;
  private:
  const ::open_vario::PingRequest& _internal_ping() const;
  public:
  const ::open_vario::PingRequest& ping() const;
  ::open_vario::PingRequest* release_ping();
  ::open_vario::PingRequest* mutable_ping();
  void set_allocated_ping(::open_vario::PingRequest* ping);

  void clear_Requests();
  RequestsCase Requests_case() const;
  // @@protoc_insertion_point(class_scope:open_vario.SimuRequest)
 private:
  void set_has_connect();
  void set_has_disconnect();
  void set_has_list_sensors();
  void set_has_update_sensor();
  void set_has_ping();

  inline bool has_Requests() const;
  inline void clear_has_Requests();

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  union RequestsUnion {
    RequestsUnion() {}
    ::open_vario::ConnectRequest* connect_;
    ::open_vario::DisconnectRequest* disconnect_;
    ::open_vario::ListSensorsRequest* list_sensors_;
    ::open_vario::UpdateSensorRequest* update_sensor_;
    ::open_vario::PingRequest* ping_;
  } Requests_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::protobuf_requests_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConnectRequest_NotificationEndpoint

// string ip_address = 1;
inline void ConnectRequest_NotificationEndpoint::clear_ip_address() {
  ip_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConnectRequest_NotificationEndpoint::ip_address() const {
  // @@protoc_insertion_point(field_get:open_vario.ConnectRequest.NotificationEndpoint.ip_address)
  return ip_address_.GetNoArena();
}
inline void ConnectRequest_NotificationEndpoint::set_ip_address(const ::std::string& value) {
  
  ip_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:open_vario.ConnectRequest.NotificationEndpoint.ip_address)
}
#if LANG_CXX11
inline void ConnectRequest_NotificationEndpoint::set_ip_address(::std::string&& value) {
  
  ip_address_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:open_vario.ConnectRequest.NotificationEndpoint.ip_address)
}
#endif
inline void ConnectRequest_NotificationEndpoint::set_ip_address(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  ip_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:open_vario.ConnectRequest.NotificationEndpoint.ip_address)
}
inline void ConnectRequest_NotificationEndpoint::set_ip_address(const char* value, size_t size) {
  
  ip_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:open_vario.ConnectRequest.NotificationEndpoint.ip_address)
}
inline ::std::string* ConnectRequest_NotificationEndpoint::mutable_ip_address() {
  
  // @@protoc_insertion_point(field_mutable:open_vario.ConnectRequest.NotificationEndpoint.ip_address)
  return ip_address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConnectRequest_NotificationEndpoint::release_ip_address() {
  // @@protoc_insertion_point(field_release:open_vario.ConnectRequest.NotificationEndpoint.ip_address)
  
  return ip_address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConnectRequest_NotificationEndpoint::set_allocated_ip_address(::std::string* ip_address) {
  if (ip_address != NULL) {
    
  } else {
    
  }
  ip_address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip_address);
  // @@protoc_insertion_point(field_set_allocated:open_vario.ConnectRequest.NotificationEndpoint.ip_address)
}

// uint32 port = 2;
inline void ConnectRequest_NotificationEndpoint::clear_port() {
  port_ = 0u;
}
inline ::google::protobuf::uint32 ConnectRequest_NotificationEndpoint::port() const {
  // @@protoc_insertion_point(field_get:open_vario.ConnectRequest.NotificationEndpoint.port)
  return port_;
}
inline void ConnectRequest_NotificationEndpoint::set_port(::google::protobuf::uint32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:open_vario.ConnectRequest.NotificationEndpoint.port)
}

// -------------------------------------------------------------------

// ConnectRequest

// .open_vario.ConnectRequest.NotificationEndpoint notification_endpoint = 1;
inline bool ConnectRequest::has_notification_endpoint() const {
  return this != internal_default_instance() && notification_endpoint_ != NULL;
}
inline void ConnectRequest::clear_notification_endpoint() {
  if (GetArenaNoVirtual() == NULL && notification_endpoint_ != NULL) {
    delete notification_endpoint_;
  }
  notification_endpoint_ = NULL;
}
inline const ::open_vario::ConnectRequest_NotificationEndpoint& ConnectRequest::_internal_notification_endpoint() const {
  return *notification_endpoint_;
}
inline const ::open_vario::ConnectRequest_NotificationEndpoint& ConnectRequest::notification_endpoint() const {
  const ::open_vario::ConnectRequest_NotificationEndpoint* p = notification_endpoint_;
  // @@protoc_insertion_point(field_get:open_vario.ConnectRequest.notification_endpoint)
  return p != NULL ? *p : *reinterpret_cast<const ::open_vario::ConnectRequest_NotificationEndpoint*>(
      &::open_vario::_ConnectRequest_NotificationEndpoint_default_instance_);
}
inline ::open_vario::ConnectRequest_NotificationEndpoint* ConnectRequest::release_notification_endpoint() {
  // @@protoc_insertion_point(field_release:open_vario.ConnectRequest.notification_endpoint)
  
  ::open_vario::ConnectRequest_NotificationEndpoint* temp = notification_endpoint_;
  notification_endpoint_ = NULL;
  return temp;
}
inline ::open_vario::ConnectRequest_NotificationEndpoint* ConnectRequest::mutable_notification_endpoint() {
  
  if (notification_endpoint_ == NULL) {
    auto* p = CreateMaybeMessage<::open_vario::ConnectRequest_NotificationEndpoint>(GetArenaNoVirtual());
    notification_endpoint_ = p;
  }
  // @@protoc_insertion_point(field_mutable:open_vario.ConnectRequest.notification_endpoint)
  return notification_endpoint_;
}
inline void ConnectRequest::set_allocated_notification_endpoint(::open_vario::ConnectRequest_NotificationEndpoint* notification_endpoint) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete notification_endpoint_;
  }
  if (notification_endpoint) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      notification_endpoint = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, notification_endpoint, submessage_arena);
    }
    
  } else {
    
  }
  notification_endpoint_ = notification_endpoint;
  // @@protoc_insertion_point(field_set_allocated:open_vario.ConnectRequest.notification_endpoint)
}

// -------------------------------------------------------------------

// DisconnectRequest

// -------------------------------------------------------------------

// ListSensorsRequest

// -------------------------------------------------------------------

// UpdateSensorRequest

// uint32 id = 1;
inline void UpdateSensorRequest::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 UpdateSensorRequest::id() const {
  // @@protoc_insertion_point(field_get:open_vario.UpdateSensorRequest.id)
  return id_;
}
inline void UpdateSensorRequest::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:open_vario.UpdateSensorRequest.id)
}

// uint32 uint_value = 2;
inline bool UpdateSensorRequest::has_uint_value() const {
  return Values_case() == kUintValue;
}
inline void UpdateSensorRequest::set_has_uint_value() {
  _oneof_case_[0] = kUintValue;
}
inline void UpdateSensorRequest::clear_uint_value() {
  if (has_uint_value()) {
    Values_.uint_value_ = 0u;
    clear_has_Values();
  }
}
inline ::google::protobuf::uint32 UpdateSensorRequest::uint_value() const {
  // @@protoc_insertion_point(field_get:open_vario.UpdateSensorRequest.uint_value)
  if (has_uint_value()) {
    return Values_.uint_value_;
  }
  return 0u;
}
inline void UpdateSensorRequest::set_uint_value(::google::protobuf::uint32 value) {
  if (!has_uint_value()) {
    clear_Values();
    set_has_uint_value();
  }
  Values_.uint_value_ = value;
  // @@protoc_insertion_point(field_set:open_vario.UpdateSensorRequest.uint_value)
}

// sint32 int_value = 3;
inline bool UpdateSensorRequest::has_int_value() const {
  return Values_case() == kIntValue;
}
inline void UpdateSensorRequest::set_has_int_value() {
  _oneof_case_[0] = kIntValue;
}
inline void UpdateSensorRequest::clear_int_value() {
  if (has_int_value()) {
    Values_.int_value_ = 0;
    clear_has_Values();
  }
}
inline ::google::protobuf::int32 UpdateSensorRequest::int_value() const {
  // @@protoc_insertion_point(field_get:open_vario.UpdateSensorRequest.int_value)
  if (has_int_value()) {
    return Values_.int_value_;
  }
  return 0;
}
inline void UpdateSensorRequest::set_int_value(::google::protobuf::int32 value) {
  if (!has_int_value()) {
    clear_Values();
    set_has_int_value();
  }
  Values_.int_value_ = value;
  // @@protoc_insertion_point(field_set:open_vario.UpdateSensorRequest.int_value)
}

// float float_value = 4;
inline bool UpdateSensorRequest::has_float_value() const {
  return Values_case() == kFloatValue;
}
inline void UpdateSensorRequest::set_has_float_value() {
  _oneof_case_[0] = kFloatValue;
}
inline void UpdateSensorRequest::clear_float_value() {
  if (has_float_value()) {
    Values_.float_value_ = 0;
    clear_has_Values();
  }
}
inline float UpdateSensorRequest::float_value() const {
  // @@protoc_insertion_point(field_get:open_vario.UpdateSensorRequest.float_value)
  if (has_float_value()) {
    return Values_.float_value_;
  }
  return 0;
}
inline void UpdateSensorRequest::set_float_value(float value) {
  if (!has_float_value()) {
    clear_Values();
    set_has_float_value();
  }
  Values_.float_value_ = value;
  // @@protoc_insertion_point(field_set:open_vario.UpdateSensorRequest.float_value)
}

// double double_value = 5;
inline bool UpdateSensorRequest::has_double_value() const {
  return Values_case() == kDoubleValue;
}
inline void UpdateSensorRequest::set_has_double_value() {
  _oneof_case_[0] = kDoubleValue;
}
inline void UpdateSensorRequest::clear_double_value() {
  if (has_double_value()) {
    Values_.double_value_ = 0;
    clear_has_Values();
  }
}
inline double UpdateSensorRequest::double_value() const {
  // @@protoc_insertion_point(field_get:open_vario.UpdateSensorRequest.double_value)
  if (has_double_value()) {
    return Values_.double_value_;
  }
  return 0;
}
inline void UpdateSensorRequest::set_double_value(double value) {
  if (!has_double_value()) {
    clear_Values();
    set_has_double_value();
  }
  Values_.double_value_ = value;
  // @@protoc_insertion_point(field_set:open_vario.UpdateSensorRequest.double_value)
}

// string string_value = 6;
inline bool UpdateSensorRequest::has_string_value() const {
  return Values_case() == kStringValue;
}
inline void UpdateSensorRequest::set_has_string_value() {
  _oneof_case_[0] = kStringValue;
}
inline void UpdateSensorRequest::clear_string_value() {
  if (has_string_value()) {
    Values_.string_value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_Values();
  }
}
inline const ::std::string& UpdateSensorRequest::string_value() const {
  // @@protoc_insertion_point(field_get:open_vario.UpdateSensorRequest.string_value)
  if (has_string_value()) {
    return Values_.string_value_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void UpdateSensorRequest::set_string_value(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:open_vario.UpdateSensorRequest.string_value)
  if (!has_string_value()) {
    clear_Values();
    set_has_string_value();
    Values_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Values_.string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:open_vario.UpdateSensorRequest.string_value)
}
#if LANG_CXX11
inline void UpdateSensorRequest::set_string_value(::std::string&& value) {
  // @@protoc_insertion_point(field_set:open_vario.UpdateSensorRequest.string_value)
  if (!has_string_value()) {
    clear_Values();
    set_has_string_value();
    Values_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Values_.string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:open_vario.UpdateSensorRequest.string_value)
}
#endif
inline void UpdateSensorRequest::set_string_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  if (!has_string_value()) {
    clear_Values();
    set_has_string_value();
    Values_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Values_.string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:open_vario.UpdateSensorRequest.string_value)
}
inline void UpdateSensorRequest::set_string_value(const char* value, size_t size) {
  if (!has_string_value()) {
    clear_Values();
    set_has_string_value();
    Values_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Values_.string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:open_vario.UpdateSensorRequest.string_value)
}
inline ::std::string* UpdateSensorRequest::mutable_string_value() {
  if (!has_string_value()) {
    clear_Values();
    set_has_string_value();
    Values_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.UpdateSensorRequest.string_value)
  return Values_.string_value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UpdateSensorRequest::release_string_value() {
  // @@protoc_insertion_point(field_release:open_vario.UpdateSensorRequest.string_value)
  if (has_string_value()) {
    clear_has_Values();
    return Values_.string_value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
inline void UpdateSensorRequest::set_allocated_string_value(::std::string* string_value) {
  if (!has_string_value()) {
    Values_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_Values();
  if (string_value != NULL) {
    set_has_string_value();
    Values_.string_value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), string_value);
  }
  // @@protoc_insertion_point(field_set_allocated:open_vario.UpdateSensorRequest.string_value)
}

// bool bool_value = 7;
inline bool UpdateSensorRequest::has_bool_value() const {
  return Values_case() == kBoolValue;
}
inline void UpdateSensorRequest::set_has_bool_value() {
  _oneof_case_[0] = kBoolValue;
}
inline void UpdateSensorRequest::clear_bool_value() {
  if (has_bool_value()) {
    Values_.bool_value_ = false;
    clear_has_Values();
  }
}
inline bool UpdateSensorRequest::bool_value() const {
  // @@protoc_insertion_point(field_get:open_vario.UpdateSensorRequest.bool_value)
  if (has_bool_value()) {
    return Values_.bool_value_;
  }
  return false;
}
inline void UpdateSensorRequest::set_bool_value(bool value) {
  if (!has_bool_value()) {
    clear_Values();
    set_has_bool_value();
  }
  Values_.bool_value_ = value;
  // @@protoc_insertion_point(field_set:open_vario.UpdateSensorRequest.bool_value)
}

inline bool UpdateSensorRequest::has_Values() const {
  return Values_case() != VALUES_NOT_SET;
}
inline void UpdateSensorRequest::clear_has_Values() {
  _oneof_case_[0] = VALUES_NOT_SET;
}
inline UpdateSensorRequest::ValuesCase UpdateSensorRequest::Values_case() const {
  return UpdateSensorRequest::ValuesCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// PingRequest

// uint32 number = 1;
inline void PingRequest::clear_number() {
  number_ = 0u;
}
inline ::google::protobuf::uint32 PingRequest::number() const {
  // @@protoc_insertion_point(field_get:open_vario.PingRequest.number)
  return number_;
}
inline void PingRequest::set_number(::google::protobuf::uint32 value) {
  
  number_ = value;
  // @@protoc_insertion_point(field_set:open_vario.PingRequest.number)
}

// -------------------------------------------------------------------

// SimuRequest

// .open_vario.ConnectRequest connect = 1;
inline bool SimuRequest::has_connect() const {
  return Requests_case() == kConnect;
}
inline void SimuRequest::set_has_connect() {
  _oneof_case_[0] = kConnect;
}
inline void SimuRequest::clear_connect() {
  if (has_connect()) {
    delete Requests_.connect_;
    clear_has_Requests();
  }
}
inline const ::open_vario::ConnectRequest& SimuRequest::_internal_connect() const {
  return *Requests_.connect_;
}
inline ::open_vario::ConnectRequest* SimuRequest::release_connect() {
  // @@protoc_insertion_point(field_release:open_vario.SimuRequest.connect)
  if (has_connect()) {
    clear_has_Requests();
      ::open_vario::ConnectRequest* temp = Requests_.connect_;
    Requests_.connect_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::ConnectRequest& SimuRequest::connect() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuRequest.connect)
  return has_connect()
      ? *Requests_.connect_
      : *reinterpret_cast< ::open_vario::ConnectRequest*>(&::open_vario::_ConnectRequest_default_instance_);
}
inline ::open_vario::ConnectRequest* SimuRequest::mutable_connect() {
  if (!has_connect()) {
    clear_Requests();
    set_has_connect();
    Requests_.connect_ = CreateMaybeMessage< ::open_vario::ConnectRequest >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuRequest.connect)
  return Requests_.connect_;
}

// .open_vario.DisconnectRequest disconnect = 2;
inline bool SimuRequest::has_disconnect() const {
  return Requests_case() == kDisconnect;
}
inline void SimuRequest::set_has_disconnect() {
  _oneof_case_[0] = kDisconnect;
}
inline void SimuRequest::clear_disconnect() {
  if (has_disconnect()) {
    delete Requests_.disconnect_;
    clear_has_Requests();
  }
}
inline const ::open_vario::DisconnectRequest& SimuRequest::_internal_disconnect() const {
  return *Requests_.disconnect_;
}
inline ::open_vario::DisconnectRequest* SimuRequest::release_disconnect() {
  // @@protoc_insertion_point(field_release:open_vario.SimuRequest.disconnect)
  if (has_disconnect()) {
    clear_has_Requests();
      ::open_vario::DisconnectRequest* temp = Requests_.disconnect_;
    Requests_.disconnect_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::DisconnectRequest& SimuRequest::disconnect() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuRequest.disconnect)
  return has_disconnect()
      ? *Requests_.disconnect_
      : *reinterpret_cast< ::open_vario::DisconnectRequest*>(&::open_vario::_DisconnectRequest_default_instance_);
}
inline ::open_vario::DisconnectRequest* SimuRequest::mutable_disconnect() {
  if (!has_disconnect()) {
    clear_Requests();
    set_has_disconnect();
    Requests_.disconnect_ = CreateMaybeMessage< ::open_vario::DisconnectRequest >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuRequest.disconnect)
  return Requests_.disconnect_;
}

// .open_vario.ListSensorsRequest list_sensors = 3;
inline bool SimuRequest::has_list_sensors() const {
  return Requests_case() == kListSensors;
}
inline void SimuRequest::set_has_list_sensors() {
  _oneof_case_[0] = kListSensors;
}
inline void SimuRequest::clear_list_sensors() {
  if (has_list_sensors()) {
    delete Requests_.list_sensors_;
    clear_has_Requests();
  }
}
inline const ::open_vario::ListSensorsRequest& SimuRequest::_internal_list_sensors() const {
  return *Requests_.list_sensors_;
}
inline ::open_vario::ListSensorsRequest* SimuRequest::release_list_sensors() {
  // @@protoc_insertion_point(field_release:open_vario.SimuRequest.list_sensors)
  if (has_list_sensors()) {
    clear_has_Requests();
      ::open_vario::ListSensorsRequest* temp = Requests_.list_sensors_;
    Requests_.list_sensors_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::ListSensorsRequest& SimuRequest::list_sensors() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuRequest.list_sensors)
  return has_list_sensors()
      ? *Requests_.list_sensors_
      : *reinterpret_cast< ::open_vario::ListSensorsRequest*>(&::open_vario::_ListSensorsRequest_default_instance_);
}
inline ::open_vario::ListSensorsRequest* SimuRequest::mutable_list_sensors() {
  if (!has_list_sensors()) {
    clear_Requests();
    set_has_list_sensors();
    Requests_.list_sensors_ = CreateMaybeMessage< ::open_vario::ListSensorsRequest >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuRequest.list_sensors)
  return Requests_.list_sensors_;
}

// .open_vario.UpdateSensorRequest update_sensor = 4;
inline bool SimuRequest::has_update_sensor() const {
  return Requests_case() == kUpdateSensor;
}
inline void SimuRequest::set_has_update_sensor() {
  _oneof_case_[0] = kUpdateSensor;
}
inline void SimuRequest::clear_update_sensor() {
  if (has_update_sensor()) {
    delete Requests_.update_sensor_;
    clear_has_Requests();
  }
}
inline const ::open_vario::UpdateSensorRequest& SimuRequest::_internal_update_sensor() const {
  return *Requests_.update_sensor_;
}
inline ::open_vario::UpdateSensorRequest* SimuRequest::release_update_sensor() {
  // @@protoc_insertion_point(field_release:open_vario.SimuRequest.update_sensor)
  if (has_update_sensor()) {
    clear_has_Requests();
      ::open_vario::UpdateSensorRequest* temp = Requests_.update_sensor_;
    Requests_.update_sensor_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::UpdateSensorRequest& SimuRequest::update_sensor() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuRequest.update_sensor)
  return has_update_sensor()
      ? *Requests_.update_sensor_
      : *reinterpret_cast< ::open_vario::UpdateSensorRequest*>(&::open_vario::_UpdateSensorRequest_default_instance_);
}
inline ::open_vario::UpdateSensorRequest* SimuRequest::mutable_update_sensor() {
  if (!has_update_sensor()) {
    clear_Requests();
    set_has_update_sensor();
    Requests_.update_sensor_ = CreateMaybeMessage< ::open_vario::UpdateSensorRequest >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuRequest.update_sensor)
  return Requests_.update_sensor_;
}

// .open_vario.PingRequest ping = 5;
inline bool SimuRequest::has_ping() const {
  return Requests_case() == kPing;
}
inline void SimuRequest::set_has_ping() {
  _oneof_case_[0] = kPing;
}
inline void SimuRequest::clear_ping() {
  if (has_ping()) {
    delete Requests_.ping_;
    clear_has_Requests();
  }
}
inline const ::open_vario::PingRequest& SimuRequest::_internal_ping() const {
  return *Requests_.ping_;
}
inline ::open_vario::PingRequest* SimuRequest::release_ping() {
  // @@protoc_insertion_point(field_release:open_vario.SimuRequest.ping)
  if (has_ping()) {
    clear_has_Requests();
      ::open_vario::PingRequest* temp = Requests_.ping_;
    Requests_.ping_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::PingRequest& SimuRequest::ping() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuRequest.ping)
  return has_ping()
      ? *Requests_.ping_
      : *reinterpret_cast< ::open_vario::PingRequest*>(&::open_vario::_PingRequest_default_instance_);
}
inline ::open_vario::PingRequest* SimuRequest::mutable_ping() {
  if (!has_ping()) {
    clear_Requests();
    set_has_ping();
    Requests_.ping_ = CreateMaybeMessage< ::open_vario::PingRequest >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuRequest.ping)
  return Requests_.ping_;
}

inline bool SimuRequest::has_Requests() const {
  return Requests_case() != REQUESTS_NOT_SET;
}
inline void SimuRequest::clear_has_Requests() {
  _oneof_case_[0] = REQUESTS_NOT_SET;
}
inline SimuRequest::RequestsCase SimuRequest::Requests_case() const {
  return SimuRequest::RequestsCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace open_vario

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_requests_2eproto
