// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responses.proto

#ifndef PROTOBUF_INCLUDED_responses_2eproto
#define PROTOBUF_INCLUDED_responses_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_responses_2eproto 

namespace protobuf_responses_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_responses_2eproto
namespace open_vario {
class ConnectResponse;
class ConnectResponseDefaultTypeInternal;
extern ConnectResponseDefaultTypeInternal _ConnectResponse_default_instance_;
class DisconnectResponse;
class DisconnectResponseDefaultTypeInternal;
extern DisconnectResponseDefaultTypeInternal _DisconnectResponse_default_instance_;
class ListSensorsResponse;
class ListSensorsResponseDefaultTypeInternal;
extern ListSensorsResponseDefaultTypeInternal _ListSensorsResponse_default_instance_;
class ListSensorsResponse_Sensor;
class ListSensorsResponse_SensorDefaultTypeInternal;
extern ListSensorsResponse_SensorDefaultTypeInternal _ListSensorsResponse_Sensor_default_instance_;
class PingResponse;
class PingResponseDefaultTypeInternal;
extern PingResponseDefaultTypeInternal _PingResponse_default_instance_;
class SimuResponse;
class SimuResponseDefaultTypeInternal;
extern SimuResponseDefaultTypeInternal _SimuResponse_default_instance_;
class UpdateSensorResponse;
class UpdateSensorResponseDefaultTypeInternal;
extern UpdateSensorResponseDefaultTypeInternal _UpdateSensorResponse_default_instance_;
}  // namespace open_vario
namespace google {
namespace protobuf {
template<> ::open_vario::ConnectResponse* Arena::CreateMaybeMessage<::open_vario::ConnectResponse>(Arena*);
template<> ::open_vario::DisconnectResponse* Arena::CreateMaybeMessage<::open_vario::DisconnectResponse>(Arena*);
template<> ::open_vario::ListSensorsResponse* Arena::CreateMaybeMessage<::open_vario::ListSensorsResponse>(Arena*);
template<> ::open_vario::ListSensorsResponse_Sensor* Arena::CreateMaybeMessage<::open_vario::ListSensorsResponse_Sensor>(Arena*);
template<> ::open_vario::PingResponse* Arena::CreateMaybeMessage<::open_vario::PingResponse>(Arena*);
template<> ::open_vario::SimuResponse* Arena::CreateMaybeMessage<::open_vario::SimuResponse>(Arena*);
template<> ::open_vario::UpdateSensorResponse* Arena::CreateMaybeMessage<::open_vario::UpdateSensorResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace open_vario {

enum ListSensorsResponse_SensorType {
  ListSensorsResponse_SensorType_ST_UNKNOWN = 0,
  ListSensorsResponse_SensorType_ST_PRESSURE = 1,
  ListSensorsResponse_SensorType_ST_TEMPERATURE = 2,
  ListSensorsResponse_SensorType_ST_ALTITUDE = 4,
  ListSensorsResponse_SensorType_ST_GNSS = 8,
  ListSensorsResponse_SensorType_ListSensorsResponse_SensorType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ListSensorsResponse_SensorType_ListSensorsResponse_SensorType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ListSensorsResponse_SensorType_IsValid(int value);
const ListSensorsResponse_SensorType ListSensorsResponse_SensorType_SensorType_MIN = ListSensorsResponse_SensorType_ST_UNKNOWN;
const ListSensorsResponse_SensorType ListSensorsResponse_SensorType_SensorType_MAX = ListSensorsResponse_SensorType_ST_GNSS;
const int ListSensorsResponse_SensorType_SensorType_ARRAYSIZE = ListSensorsResponse_SensorType_SensorType_MAX + 1;

enum ListSensorsResponse_SensorValueType {
  ListSensorsResponse_SensorValueType_SVT_UNKNOWN = 0,
  ListSensorsResponse_SensorValueType_SVT_UINT = 1,
  ListSensorsResponse_SensorValueType_SVT_INT = 2,
  ListSensorsResponse_SensorValueType_SVT_FLOAT = 3,
  ListSensorsResponse_SensorValueType_SVT_DOUBLE = 4,
  ListSensorsResponse_SensorValueType_SVT_STRING = 5,
  ListSensorsResponse_SensorValueType_SVT_BOOL = 6,
  ListSensorsResponse_SensorValueType_ListSensorsResponse_SensorValueType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ListSensorsResponse_SensorValueType_ListSensorsResponse_SensorValueType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ListSensorsResponse_SensorValueType_IsValid(int value);
const ListSensorsResponse_SensorValueType ListSensorsResponse_SensorValueType_SensorValueType_MIN = ListSensorsResponse_SensorValueType_SVT_UNKNOWN;
const ListSensorsResponse_SensorValueType ListSensorsResponse_SensorValueType_SensorValueType_MAX = ListSensorsResponse_SensorValueType_SVT_BOOL;
const int ListSensorsResponse_SensorValueType_SensorValueType_ARRAYSIZE = ListSensorsResponse_SensorValueType_SensorValueType_MAX + 1;

// ===================================================================

class ConnectResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.ConnectResponse) */ {
 public:
  ConnectResponse();
  virtual ~ConnectResponse();

  ConnectResponse(const ConnectResponse& from);

  inline ConnectResponse& operator=(const ConnectResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConnectResponse(ConnectResponse&& from) noexcept
    : ConnectResponse() {
    *this = ::std::move(from);
  }

  inline ConnectResponse& operator=(ConnectResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ConnectResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConnectResponse* internal_default_instance() {
    return reinterpret_cast<const ConnectResponse*>(
               &_ConnectResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ConnectResponse* other);
  friend void swap(ConnectResponse& a, ConnectResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConnectResponse* New() const final {
    return CreateMaybeMessage<ConnectResponse>(NULL);
  }

  ConnectResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConnectResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ConnectResponse& from);
  void MergeFrom(const ConnectResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ConnectResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool accept = 1;
  void clear_accept();
  static const int kAcceptFieldNumber = 1;
  bool accept() const;
  void set_accept(bool value);

  // @@protoc_insertion_point(class_scope:open_vario.ConnectResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  bool accept_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_responses_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DisconnectResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.DisconnectResponse) */ {
 public:
  DisconnectResponse();
  virtual ~DisconnectResponse();

  DisconnectResponse(const DisconnectResponse& from);

  inline DisconnectResponse& operator=(const DisconnectResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DisconnectResponse(DisconnectResponse&& from) noexcept
    : DisconnectResponse() {
    *this = ::std::move(from);
  }

  inline DisconnectResponse& operator=(DisconnectResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const DisconnectResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DisconnectResponse* internal_default_instance() {
    return reinterpret_cast<const DisconnectResponse*>(
               &_DisconnectResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(DisconnectResponse* other);
  friend void swap(DisconnectResponse& a, DisconnectResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DisconnectResponse* New() const final {
    return CreateMaybeMessage<DisconnectResponse>(NULL);
  }

  DisconnectResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DisconnectResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const DisconnectResponse& from);
  void MergeFrom(const DisconnectResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DisconnectResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:open_vario.DisconnectResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_responses_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ListSensorsResponse_Sensor : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.ListSensorsResponse.Sensor) */ {
 public:
  ListSensorsResponse_Sensor();
  virtual ~ListSensorsResponse_Sensor();

  ListSensorsResponse_Sensor(const ListSensorsResponse_Sensor& from);

  inline ListSensorsResponse_Sensor& operator=(const ListSensorsResponse_Sensor& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ListSensorsResponse_Sensor(ListSensorsResponse_Sensor&& from) noexcept
    : ListSensorsResponse_Sensor() {
    *this = ::std::move(from);
  }

  inline ListSensorsResponse_Sensor& operator=(ListSensorsResponse_Sensor&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ListSensorsResponse_Sensor& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ListSensorsResponse_Sensor* internal_default_instance() {
    return reinterpret_cast<const ListSensorsResponse_Sensor*>(
               &_ListSensorsResponse_Sensor_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ListSensorsResponse_Sensor* other);
  friend void swap(ListSensorsResponse_Sensor& a, ListSensorsResponse_Sensor& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ListSensorsResponse_Sensor* New() const final {
    return CreateMaybeMessage<ListSensorsResponse_Sensor>(NULL);
  }

  ListSensorsResponse_Sensor* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ListSensorsResponse_Sensor>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ListSensorsResponse_Sensor& from);
  void MergeFrom(const ListSensorsResponse_Sensor& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListSensorsResponse_Sensor* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // .open_vario.ListSensorsResponse.SensorType type = 3;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  ::open_vario::ListSensorsResponse_SensorType type() const;
  void set_type(::open_vario::ListSensorsResponse_SensorType value);

  // .open_vario.ListSensorsResponse.SensorValueType value_type = 4;
  void clear_value_type();
  static const int kValueTypeFieldNumber = 4;
  ::open_vario::ListSensorsResponse_SensorValueType value_type() const;
  void set_value_type(::open_vario::ListSensorsResponse_SensorValueType value);

  // @@protoc_insertion_point(class_scope:open_vario.ListSensorsResponse.Sensor)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint32 id_;
  int type_;
  int value_type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_responses_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ListSensorsResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.ListSensorsResponse) */ {
 public:
  ListSensorsResponse();
  virtual ~ListSensorsResponse();

  ListSensorsResponse(const ListSensorsResponse& from);

  inline ListSensorsResponse& operator=(const ListSensorsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ListSensorsResponse(ListSensorsResponse&& from) noexcept
    : ListSensorsResponse() {
    *this = ::std::move(from);
  }

  inline ListSensorsResponse& operator=(ListSensorsResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ListSensorsResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ListSensorsResponse* internal_default_instance() {
    return reinterpret_cast<const ListSensorsResponse*>(
               &_ListSensorsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ListSensorsResponse* other);
  friend void swap(ListSensorsResponse& a, ListSensorsResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ListSensorsResponse* New() const final {
    return CreateMaybeMessage<ListSensorsResponse>(NULL);
  }

  ListSensorsResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ListSensorsResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ListSensorsResponse& from);
  void MergeFrom(const ListSensorsResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListSensorsResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef ListSensorsResponse_Sensor Sensor;

  typedef ListSensorsResponse_SensorType SensorType;
  static const SensorType ST_UNKNOWN =
    ListSensorsResponse_SensorType_ST_UNKNOWN;
  static const SensorType ST_PRESSURE =
    ListSensorsResponse_SensorType_ST_PRESSURE;
  static const SensorType ST_TEMPERATURE =
    ListSensorsResponse_SensorType_ST_TEMPERATURE;
  static const SensorType ST_ALTITUDE =
    ListSensorsResponse_SensorType_ST_ALTITUDE;
  static const SensorType ST_GNSS =
    ListSensorsResponse_SensorType_ST_GNSS;
  static inline bool SensorType_IsValid(int value) {
    return ListSensorsResponse_SensorType_IsValid(value);
  }
  static const SensorType SensorType_MIN =
    ListSensorsResponse_SensorType_SensorType_MIN;
  static const SensorType SensorType_MAX =
    ListSensorsResponse_SensorType_SensorType_MAX;
  static const int SensorType_ARRAYSIZE =
    ListSensorsResponse_SensorType_SensorType_ARRAYSIZE;

  typedef ListSensorsResponse_SensorValueType SensorValueType;
  static const SensorValueType SVT_UNKNOWN =
    ListSensorsResponse_SensorValueType_SVT_UNKNOWN;
  static const SensorValueType SVT_UINT =
    ListSensorsResponse_SensorValueType_SVT_UINT;
  static const SensorValueType SVT_INT =
    ListSensorsResponse_SensorValueType_SVT_INT;
  static const SensorValueType SVT_FLOAT =
    ListSensorsResponse_SensorValueType_SVT_FLOAT;
  static const SensorValueType SVT_DOUBLE =
    ListSensorsResponse_SensorValueType_SVT_DOUBLE;
  static const SensorValueType SVT_STRING =
    ListSensorsResponse_SensorValueType_SVT_STRING;
  static const SensorValueType SVT_BOOL =
    ListSensorsResponse_SensorValueType_SVT_BOOL;
  static inline bool SensorValueType_IsValid(int value) {
    return ListSensorsResponse_SensorValueType_IsValid(value);
  }
  static const SensorValueType SensorValueType_MIN =
    ListSensorsResponse_SensorValueType_SensorValueType_MIN;
  static const SensorValueType SensorValueType_MAX =
    ListSensorsResponse_SensorValueType_SensorValueType_MAX;
  static const int SensorValueType_ARRAYSIZE =
    ListSensorsResponse_SensorValueType_SensorValueType_ARRAYSIZE;

  // accessors -------------------------------------------------------

  // repeated .open_vario.ListSensorsResponse.Sensor sensors = 1;
  int sensors_size() const;
  void clear_sensors();
  static const int kSensorsFieldNumber = 1;
  ::open_vario::ListSensorsResponse_Sensor* mutable_sensors(int index);
  ::google::protobuf::RepeatedPtrField< ::open_vario::ListSensorsResponse_Sensor >*
      mutable_sensors();
  const ::open_vario::ListSensorsResponse_Sensor& sensors(int index) const;
  ::open_vario::ListSensorsResponse_Sensor* add_sensors();
  const ::google::protobuf::RepeatedPtrField< ::open_vario::ListSensorsResponse_Sensor >&
      sensors() const;

  // @@protoc_insertion_point(class_scope:open_vario.ListSensorsResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::open_vario::ListSensorsResponse_Sensor > sensors_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_responses_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UpdateSensorResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.UpdateSensorResponse) */ {
 public:
  UpdateSensorResponse();
  virtual ~UpdateSensorResponse();

  UpdateSensorResponse(const UpdateSensorResponse& from);

  inline UpdateSensorResponse& operator=(const UpdateSensorResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UpdateSensorResponse(UpdateSensorResponse&& from) noexcept
    : UpdateSensorResponse() {
    *this = ::std::move(from);
  }

  inline UpdateSensorResponse& operator=(UpdateSensorResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const UpdateSensorResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateSensorResponse* internal_default_instance() {
    return reinterpret_cast<const UpdateSensorResponse*>(
               &_UpdateSensorResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(UpdateSensorResponse* other);
  friend void swap(UpdateSensorResponse& a, UpdateSensorResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UpdateSensorResponse* New() const final {
    return CreateMaybeMessage<UpdateSensorResponse>(NULL);
  }

  UpdateSensorResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UpdateSensorResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const UpdateSensorResponse& from);
  void MergeFrom(const UpdateSensorResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateSensorResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool success = 1;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:open_vario.UpdateSensorResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  bool success_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_responses_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PingResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.PingResponse) */ {
 public:
  PingResponse();
  virtual ~PingResponse();

  PingResponse(const PingResponse& from);

  inline PingResponse& operator=(const PingResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PingResponse(PingResponse&& from) noexcept
    : PingResponse() {
    *this = ::std::move(from);
  }

  inline PingResponse& operator=(PingResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const PingResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PingResponse* internal_default_instance() {
    return reinterpret_cast<const PingResponse*>(
               &_PingResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(PingResponse* other);
  friend void swap(PingResponse& a, PingResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PingResponse* New() const final {
    return CreateMaybeMessage<PingResponse>(NULL);
  }

  PingResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PingResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const PingResponse& from);
  void MergeFrom(const PingResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PingResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 number = 1;
  void clear_number();
  static const int kNumberFieldNumber = 1;
  ::google::protobuf::uint32 number() const;
  void set_number(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:open_vario.PingResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::uint32 number_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_responses_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SimuResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:open_vario.SimuResponse) */ {
 public:
  SimuResponse();
  virtual ~SimuResponse();

  SimuResponse(const SimuResponse& from);

  inline SimuResponse& operator=(const SimuResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SimuResponse(SimuResponse&& from) noexcept
    : SimuResponse() {
    *this = ::std::move(from);
  }

  inline SimuResponse& operator=(SimuResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const SimuResponse& default_instance();

  enum ResponsesCase {
    kConnect = 1,
    kDisconnect = 2,
    kListSensors = 3,
    kUpdateSensor = 4,
    kPing = 5,
    RESPONSES_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SimuResponse* internal_default_instance() {
    return reinterpret_cast<const SimuResponse*>(
               &_SimuResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(SimuResponse* other);
  friend void swap(SimuResponse& a, SimuResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SimuResponse* New() const final {
    return CreateMaybeMessage<SimuResponse>(NULL);
  }

  SimuResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SimuResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const SimuResponse& from);
  void MergeFrom(const SimuResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SimuResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .open_vario.ConnectResponse connect = 1;
  bool has_connect() const;
  void clear_connect();
  static const int kConnectFieldNumber = 1;
  private:
  const ::open_vario::ConnectResponse& _internal_connect() const;
  public:
  const ::open_vario::ConnectResponse& connect() const;
  ::open_vario::ConnectResponse* release_connect();
  ::open_vario::ConnectResponse* mutable_connect();
  void set_allocated_connect(::open_vario::ConnectResponse* connect);

  // .open_vario.DisconnectResponse disconnect = 2;
  bool has_disconnect() const;
  void clear_disconnect();
  static const int kDisconnectFieldNumber = 2;
  private:
  const ::open_vario::DisconnectResponse& _internal_disconnect() const;
  public:
  const ::open_vario::DisconnectResponse& disconnect() const;
  ::open_vario::DisconnectResponse* release_disconnect();
  ::open_vario::DisconnectResponse* mutable_disconnect();
  void set_allocated_disconnect(::open_vario::DisconnectResponse* disconnect);

  // .open_vario.ListSensorsResponse list_sensors = 3;
  bool has_list_sensors() const;
  void clear_list_sensors();
  static const int kListSensorsFieldNumber = 3;
  private:
  const ::open_vario::ListSensorsResponse& _internal_list_sensors() const;
  public:
  const ::open_vario::ListSensorsResponse& list_sensors() const;
  ::open_vario::ListSensorsResponse* release_list_sensors();
  ::open_vario::ListSensorsResponse* mutable_list_sensors();
  void set_allocated_list_sensors(::open_vario::ListSensorsResponse* list_sensors);

  // .open_vario.UpdateSensorResponse update_sensor = 4;
  bool has_update_sensor() const;
  void clear_update_sensor();
  static const int kUpdateSensorFieldNumber = 4;
  private:
  const ::open_vario::UpdateSensorResponse& _internal_update_sensor() const;
  public:
  const ::open_vario::UpdateSensorResponse& update_sensor() const;
  ::open_vario::UpdateSensorResponse* release_update_sensor();
  ::open_vario::UpdateSensorResponse* mutable_update_sensor();
  void set_allocated_update_sensor(::open_vario::UpdateSensorResponse* update_sensor);

  // .open_vario.PingResponse ping = 5;
  bool has_ping() const;
  void clear_ping();
  static const int kPingFieldNumber = 5;
  private:
  const ::open_vario::PingResponse& _internal_ping() const;
  public:
  const ::open_vario::PingResponse& ping() const;
  ::open_vario::PingResponse* release_ping();
  ::open_vario::PingResponse* mutable_ping();
  void set_allocated_ping(::open_vario::PingResponse* ping);

  void clear_Responses();
  ResponsesCase Responses_case() const;
  // @@protoc_insertion_point(class_scope:open_vario.SimuResponse)
 private:
  void set_has_connect();
  void set_has_disconnect();
  void set_has_list_sensors();
  void set_has_update_sensor();
  void set_has_ping();

  inline bool has_Responses() const;
  inline void clear_has_Responses();

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  union ResponsesUnion {
    ResponsesUnion() {}
    ::open_vario::ConnectResponse* connect_;
    ::open_vario::DisconnectResponse* disconnect_;
    ::open_vario::ListSensorsResponse* list_sensors_;
    ::open_vario::UpdateSensorResponse* update_sensor_;
    ::open_vario::PingResponse* ping_;
  } Responses_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::protobuf_responses_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConnectResponse

// bool accept = 1;
inline void ConnectResponse::clear_accept() {
  accept_ = false;
}
inline bool ConnectResponse::accept() const {
  // @@protoc_insertion_point(field_get:open_vario.ConnectResponse.accept)
  return accept_;
}
inline void ConnectResponse::set_accept(bool value) {
  
  accept_ = value;
  // @@protoc_insertion_point(field_set:open_vario.ConnectResponse.accept)
}

// -------------------------------------------------------------------

// DisconnectResponse

// -------------------------------------------------------------------

// ListSensorsResponse_Sensor

// uint32 id = 1;
inline void ListSensorsResponse_Sensor::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 ListSensorsResponse_Sensor::id() const {
  // @@protoc_insertion_point(field_get:open_vario.ListSensorsResponse.Sensor.id)
  return id_;
}
inline void ListSensorsResponse_Sensor::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:open_vario.ListSensorsResponse.Sensor.id)
}

// string name = 2;
inline void ListSensorsResponse_Sensor::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ListSensorsResponse_Sensor::name() const {
  // @@protoc_insertion_point(field_get:open_vario.ListSensorsResponse.Sensor.name)
  return name_.GetNoArena();
}
inline void ListSensorsResponse_Sensor::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:open_vario.ListSensorsResponse.Sensor.name)
}
#if LANG_CXX11
inline void ListSensorsResponse_Sensor::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:open_vario.ListSensorsResponse.Sensor.name)
}
#endif
inline void ListSensorsResponse_Sensor::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:open_vario.ListSensorsResponse.Sensor.name)
}
inline void ListSensorsResponse_Sensor::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:open_vario.ListSensorsResponse.Sensor.name)
}
inline ::std::string* ListSensorsResponse_Sensor::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:open_vario.ListSensorsResponse.Sensor.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ListSensorsResponse_Sensor::release_name() {
  // @@protoc_insertion_point(field_release:open_vario.ListSensorsResponse.Sensor.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ListSensorsResponse_Sensor::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:open_vario.ListSensorsResponse.Sensor.name)
}

// .open_vario.ListSensorsResponse.SensorType type = 3;
inline void ListSensorsResponse_Sensor::clear_type() {
  type_ = 0;
}
inline ::open_vario::ListSensorsResponse_SensorType ListSensorsResponse_Sensor::type() const {
  // @@protoc_insertion_point(field_get:open_vario.ListSensorsResponse.Sensor.type)
  return static_cast< ::open_vario::ListSensorsResponse_SensorType >(type_);
}
inline void ListSensorsResponse_Sensor::set_type(::open_vario::ListSensorsResponse_SensorType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:open_vario.ListSensorsResponse.Sensor.type)
}

// .open_vario.ListSensorsResponse.SensorValueType value_type = 4;
inline void ListSensorsResponse_Sensor::clear_value_type() {
  value_type_ = 0;
}
inline ::open_vario::ListSensorsResponse_SensorValueType ListSensorsResponse_Sensor::value_type() const {
  // @@protoc_insertion_point(field_get:open_vario.ListSensorsResponse.Sensor.value_type)
  return static_cast< ::open_vario::ListSensorsResponse_SensorValueType >(value_type_);
}
inline void ListSensorsResponse_Sensor::set_value_type(::open_vario::ListSensorsResponse_SensorValueType value) {
  
  value_type_ = value;
  // @@protoc_insertion_point(field_set:open_vario.ListSensorsResponse.Sensor.value_type)
}

// -------------------------------------------------------------------

// ListSensorsResponse

// repeated .open_vario.ListSensorsResponse.Sensor sensors = 1;
inline int ListSensorsResponse::sensors_size() const {
  return sensors_.size();
}
inline void ListSensorsResponse::clear_sensors() {
  sensors_.Clear();
}
inline ::open_vario::ListSensorsResponse_Sensor* ListSensorsResponse::mutable_sensors(int index) {
  // @@protoc_insertion_point(field_mutable:open_vario.ListSensorsResponse.sensors)
  return sensors_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::open_vario::ListSensorsResponse_Sensor >*
ListSensorsResponse::mutable_sensors() {
  // @@protoc_insertion_point(field_mutable_list:open_vario.ListSensorsResponse.sensors)
  return &sensors_;
}
inline const ::open_vario::ListSensorsResponse_Sensor& ListSensorsResponse::sensors(int index) const {
  // @@protoc_insertion_point(field_get:open_vario.ListSensorsResponse.sensors)
  return sensors_.Get(index);
}
inline ::open_vario::ListSensorsResponse_Sensor* ListSensorsResponse::add_sensors() {
  // @@protoc_insertion_point(field_add:open_vario.ListSensorsResponse.sensors)
  return sensors_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::open_vario::ListSensorsResponse_Sensor >&
ListSensorsResponse::sensors() const {
  // @@protoc_insertion_point(field_list:open_vario.ListSensorsResponse.sensors)
  return sensors_;
}

// -------------------------------------------------------------------

// UpdateSensorResponse

// bool success = 1;
inline void UpdateSensorResponse::clear_success() {
  success_ = false;
}
inline bool UpdateSensorResponse::success() const {
  // @@protoc_insertion_point(field_get:open_vario.UpdateSensorResponse.success)
  return success_;
}
inline void UpdateSensorResponse::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:open_vario.UpdateSensorResponse.success)
}

// -------------------------------------------------------------------

// PingResponse

// uint32 number = 1;
inline void PingResponse::clear_number() {
  number_ = 0u;
}
inline ::google::protobuf::uint32 PingResponse::number() const {
  // @@protoc_insertion_point(field_get:open_vario.PingResponse.number)
  return number_;
}
inline void PingResponse::set_number(::google::protobuf::uint32 value) {
  
  number_ = value;
  // @@protoc_insertion_point(field_set:open_vario.PingResponse.number)
}

// -------------------------------------------------------------------

// SimuResponse

// .open_vario.ConnectResponse connect = 1;
inline bool SimuResponse::has_connect() const {
  return Responses_case() == kConnect;
}
inline void SimuResponse::set_has_connect() {
  _oneof_case_[0] = kConnect;
}
inline void SimuResponse::clear_connect() {
  if (has_connect()) {
    delete Responses_.connect_;
    clear_has_Responses();
  }
}
inline const ::open_vario::ConnectResponse& SimuResponse::_internal_connect() const {
  return *Responses_.connect_;
}
inline ::open_vario::ConnectResponse* SimuResponse::release_connect() {
  // @@protoc_insertion_point(field_release:open_vario.SimuResponse.connect)
  if (has_connect()) {
    clear_has_Responses();
      ::open_vario::ConnectResponse* temp = Responses_.connect_;
    Responses_.connect_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::ConnectResponse& SimuResponse::connect() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuResponse.connect)
  return has_connect()
      ? *Responses_.connect_
      : *reinterpret_cast< ::open_vario::ConnectResponse*>(&::open_vario::_ConnectResponse_default_instance_);
}
inline ::open_vario::ConnectResponse* SimuResponse::mutable_connect() {
  if (!has_connect()) {
    clear_Responses();
    set_has_connect();
    Responses_.connect_ = CreateMaybeMessage< ::open_vario::ConnectResponse >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuResponse.connect)
  return Responses_.connect_;
}

// .open_vario.DisconnectResponse disconnect = 2;
inline bool SimuResponse::has_disconnect() const {
  return Responses_case() == kDisconnect;
}
inline void SimuResponse::set_has_disconnect() {
  _oneof_case_[0] = kDisconnect;
}
inline void SimuResponse::clear_disconnect() {
  if (has_disconnect()) {
    delete Responses_.disconnect_;
    clear_has_Responses();
  }
}
inline const ::open_vario::DisconnectResponse& SimuResponse::_internal_disconnect() const {
  return *Responses_.disconnect_;
}
inline ::open_vario::DisconnectResponse* SimuResponse::release_disconnect() {
  // @@protoc_insertion_point(field_release:open_vario.SimuResponse.disconnect)
  if (has_disconnect()) {
    clear_has_Responses();
      ::open_vario::DisconnectResponse* temp = Responses_.disconnect_;
    Responses_.disconnect_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::DisconnectResponse& SimuResponse::disconnect() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuResponse.disconnect)
  return has_disconnect()
      ? *Responses_.disconnect_
      : *reinterpret_cast< ::open_vario::DisconnectResponse*>(&::open_vario::_DisconnectResponse_default_instance_);
}
inline ::open_vario::DisconnectResponse* SimuResponse::mutable_disconnect() {
  if (!has_disconnect()) {
    clear_Responses();
    set_has_disconnect();
    Responses_.disconnect_ = CreateMaybeMessage< ::open_vario::DisconnectResponse >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuResponse.disconnect)
  return Responses_.disconnect_;
}

// .open_vario.ListSensorsResponse list_sensors = 3;
inline bool SimuResponse::has_list_sensors() const {
  return Responses_case() == kListSensors;
}
inline void SimuResponse::set_has_list_sensors() {
  _oneof_case_[0] = kListSensors;
}
inline void SimuResponse::clear_list_sensors() {
  if (has_list_sensors()) {
    delete Responses_.list_sensors_;
    clear_has_Responses();
  }
}
inline const ::open_vario::ListSensorsResponse& SimuResponse::_internal_list_sensors() const {
  return *Responses_.list_sensors_;
}
inline ::open_vario::ListSensorsResponse* SimuResponse::release_list_sensors() {
  // @@protoc_insertion_point(field_release:open_vario.SimuResponse.list_sensors)
  if (has_list_sensors()) {
    clear_has_Responses();
      ::open_vario::ListSensorsResponse* temp = Responses_.list_sensors_;
    Responses_.list_sensors_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::ListSensorsResponse& SimuResponse::list_sensors() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuResponse.list_sensors)
  return has_list_sensors()
      ? *Responses_.list_sensors_
      : *reinterpret_cast< ::open_vario::ListSensorsResponse*>(&::open_vario::_ListSensorsResponse_default_instance_);
}
inline ::open_vario::ListSensorsResponse* SimuResponse::mutable_list_sensors() {
  if (!has_list_sensors()) {
    clear_Responses();
    set_has_list_sensors();
    Responses_.list_sensors_ = CreateMaybeMessage< ::open_vario::ListSensorsResponse >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuResponse.list_sensors)
  return Responses_.list_sensors_;
}

// .open_vario.UpdateSensorResponse update_sensor = 4;
inline bool SimuResponse::has_update_sensor() const {
  return Responses_case() == kUpdateSensor;
}
inline void SimuResponse::set_has_update_sensor() {
  _oneof_case_[0] = kUpdateSensor;
}
inline void SimuResponse::clear_update_sensor() {
  if (has_update_sensor()) {
    delete Responses_.update_sensor_;
    clear_has_Responses();
  }
}
inline const ::open_vario::UpdateSensorResponse& SimuResponse::_internal_update_sensor() const {
  return *Responses_.update_sensor_;
}
inline ::open_vario::UpdateSensorResponse* SimuResponse::release_update_sensor() {
  // @@protoc_insertion_point(field_release:open_vario.SimuResponse.update_sensor)
  if (has_update_sensor()) {
    clear_has_Responses();
      ::open_vario::UpdateSensorResponse* temp = Responses_.update_sensor_;
    Responses_.update_sensor_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::UpdateSensorResponse& SimuResponse::update_sensor() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuResponse.update_sensor)
  return has_update_sensor()
      ? *Responses_.update_sensor_
      : *reinterpret_cast< ::open_vario::UpdateSensorResponse*>(&::open_vario::_UpdateSensorResponse_default_instance_);
}
inline ::open_vario::UpdateSensorResponse* SimuResponse::mutable_update_sensor() {
  if (!has_update_sensor()) {
    clear_Responses();
    set_has_update_sensor();
    Responses_.update_sensor_ = CreateMaybeMessage< ::open_vario::UpdateSensorResponse >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuResponse.update_sensor)
  return Responses_.update_sensor_;
}

// .open_vario.PingResponse ping = 5;
inline bool SimuResponse::has_ping() const {
  return Responses_case() == kPing;
}
inline void SimuResponse::set_has_ping() {
  _oneof_case_[0] = kPing;
}
inline void SimuResponse::clear_ping() {
  if (has_ping()) {
    delete Responses_.ping_;
    clear_has_Responses();
  }
}
inline const ::open_vario::PingResponse& SimuResponse::_internal_ping() const {
  return *Responses_.ping_;
}
inline ::open_vario::PingResponse* SimuResponse::release_ping() {
  // @@protoc_insertion_point(field_release:open_vario.SimuResponse.ping)
  if (has_ping()) {
    clear_has_Responses();
      ::open_vario::PingResponse* temp = Responses_.ping_;
    Responses_.ping_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::open_vario::PingResponse& SimuResponse::ping() const {
  // @@protoc_insertion_point(field_get:open_vario.SimuResponse.ping)
  return has_ping()
      ? *Responses_.ping_
      : *reinterpret_cast< ::open_vario::PingResponse*>(&::open_vario::_PingResponse_default_instance_);
}
inline ::open_vario::PingResponse* SimuResponse::mutable_ping() {
  if (!has_ping()) {
    clear_Responses();
    set_has_ping();
    Responses_.ping_ = CreateMaybeMessage< ::open_vario::PingResponse >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:open_vario.SimuResponse.ping)
  return Responses_.ping_;
}

inline bool SimuResponse::has_Responses() const {
  return Responses_case() != RESPONSES_NOT_SET;
}
inline void SimuResponse::clear_has_Responses() {
  _oneof_case_[0] = RESPONSES_NOT_SET;
}
inline SimuResponse::ResponsesCase SimuResponse::Responses_case() const {
  return SimuResponse::ResponsesCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace open_vario

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::open_vario::ListSensorsResponse_SensorType> : ::std::true_type {};
template <> struct is_proto_enum< ::open_vario::ListSensorsResponse_SensorValueType> : ::std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_responses_2eproto
