// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responses.proto

#include "responses.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_responses_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_responses_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ConnectResponse;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_responses_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_DisconnectResponse;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_responses_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ListSensorsResponse_Sensor;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_responses_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PingResponse;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_responses_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_UpdateSensorResponse;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_responses_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_ListSensorsResponse;
}  // namespace protobuf_responses_2eproto
namespace open_vario {
class ConnectResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ConnectResponse>
      _instance;
} _ConnectResponse_default_instance_;
class DisconnectResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DisconnectResponse>
      _instance;
} _DisconnectResponse_default_instance_;
class ListSensorsResponse_SensorDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ListSensorsResponse_Sensor>
      _instance;
} _ListSensorsResponse_Sensor_default_instance_;
class ListSensorsResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ListSensorsResponse>
      _instance;
} _ListSensorsResponse_default_instance_;
class UpdateSensorResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UpdateSensorResponse>
      _instance;
} _UpdateSensorResponse_default_instance_;
class PingResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PingResponse>
      _instance;
} _PingResponse_default_instance_;
class SimuResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SimuResponse>
      _instance;
  const ::open_vario::ConnectResponse* connect_;
  const ::open_vario::DisconnectResponse* disconnect_;
  const ::open_vario::ListSensorsResponse* list_sensors_;
  const ::open_vario::UpdateSensorResponse* update_sensor_;
  const ::open_vario::PingResponse* ping_;
} _SimuResponse_default_instance_;
}  // namespace open_vario
namespace protobuf_responses_2eproto {
static void InitDefaultsConnectResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_ConnectResponse_default_instance_;
    new (ptr) ::open_vario::ConnectResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::ConnectResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ConnectResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsConnectResponse}, {}};

static void InitDefaultsDisconnectResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_DisconnectResponse_default_instance_;
    new (ptr) ::open_vario::DisconnectResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::DisconnectResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DisconnectResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDisconnectResponse}, {}};

static void InitDefaultsListSensorsResponse_Sensor() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_ListSensorsResponse_Sensor_default_instance_;
    new (ptr) ::open_vario::ListSensorsResponse_Sensor();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::ListSensorsResponse_Sensor::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ListSensorsResponse_Sensor =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsListSensorsResponse_Sensor}, {}};

static void InitDefaultsListSensorsResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_ListSensorsResponse_default_instance_;
    new (ptr) ::open_vario::ListSensorsResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::ListSensorsResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ListSensorsResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsListSensorsResponse}, {
      &protobuf_responses_2eproto::scc_info_ListSensorsResponse_Sensor.base,}};

static void InitDefaultsUpdateSensorResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_UpdateSensorResponse_default_instance_;
    new (ptr) ::open_vario::UpdateSensorResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::UpdateSensorResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_UpdateSensorResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsUpdateSensorResponse}, {}};

static void InitDefaultsPingResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_PingResponse_default_instance_;
    new (ptr) ::open_vario::PingResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::PingResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PingResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPingResponse}, {}};

static void InitDefaultsSimuResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::open_vario::_SimuResponse_default_instance_;
    new (ptr) ::open_vario::SimuResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::open_vario::SimuResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<5> scc_info_SimuResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 5, InitDefaultsSimuResponse}, {
      &protobuf_responses_2eproto::scc_info_ConnectResponse.base,
      &protobuf_responses_2eproto::scc_info_DisconnectResponse.base,
      &protobuf_responses_2eproto::scc_info_ListSensorsResponse.base,
      &protobuf_responses_2eproto::scc_info_UpdateSensorResponse.base,
      &protobuf_responses_2eproto::scc_info_PingResponse.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ConnectResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DisconnectResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ListSensorsResponse_Sensor.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ListSensorsResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_UpdateSensorResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PingResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SimuResponse.base);
}

::google::protobuf::Metadata file_level_metadata[7];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::ConnectResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::ConnectResponse, accept_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::DisconnectResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::ListSensorsResponse_Sensor, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::ListSensorsResponse_Sensor, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::ListSensorsResponse_Sensor, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::ListSensorsResponse_Sensor, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::ListSensorsResponse_Sensor, value_type_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::ListSensorsResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::ListSensorsResponse, sensors_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::UpdateSensorResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::UpdateSensorResponse, success_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::PingResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::PingResponse, number_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::SimuResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::SimuResponse, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  offsetof(::open_vario::SimuResponseDefaultTypeInternal, connect_),
  offsetof(::open_vario::SimuResponseDefaultTypeInternal, disconnect_),
  offsetof(::open_vario::SimuResponseDefaultTypeInternal, list_sensors_),
  offsetof(::open_vario::SimuResponseDefaultTypeInternal, update_sensor_),
  offsetof(::open_vario::SimuResponseDefaultTypeInternal, ping_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::open_vario::SimuResponse, Responses_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::open_vario::ConnectResponse)},
  { 6, -1, sizeof(::open_vario::DisconnectResponse)},
  { 11, -1, sizeof(::open_vario::ListSensorsResponse_Sensor)},
  { 20, -1, sizeof(::open_vario::ListSensorsResponse)},
  { 26, -1, sizeof(::open_vario::UpdateSensorResponse)},
  { 32, -1, sizeof(::open_vario::PingResponse)},
  { 38, -1, sizeof(::open_vario::SimuResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::open_vario::_ConnectResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::open_vario::_DisconnectResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::open_vario::_ListSensorsResponse_Sensor_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::open_vario::_ListSensorsResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::open_vario::_UpdateSensorResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::open_vario::_PingResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::open_vario::_SimuResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "responses.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 7);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017responses.proto\022\nopen_vario\"!\n\017Connect"
      "Response\022\016\n\006accept\030\001 \001(\010\"\024\n\022DisconnectRe"
      "sponse\"\317\003\n\023ListSensorsResponse\0227\n\007sensor"
      "s\030\001 \003(\0132&.open_vario.ListSensorsResponse"
      ".Sensor\032\241\001\n\006Sensor\022\n\n\002id\030\001 \001(\r\022\014\n\004name\030\002"
      " \001(\t\0228\n\004type\030\003 \001(\0162*.open_vario.ListSens"
      "orsResponse.SensorType\022C\n\nvalue_type\030\004 \001"
      "(\0162/.open_vario.ListSensorsResponse.Sens"
      "orValueType\"_\n\nSensorType\022\016\n\nST_UNKNOWN\020"
      "\000\022\017\n\013ST_PRESSURE\020\001\022\022\n\016ST_TEMPERATURE\020\002\022\017"
      "\n\013ST_ALTITUDE\020\004\022\013\n\007ST_GNSS\020\010\"z\n\017SensorVa"
      "lueType\022\017\n\013SVT_UNKNOWN\020\000\022\014\n\010SVT_UINT\020\001\022\013"
      "\n\007SVT_INT\020\002\022\r\n\tSVT_FLOAT\020\003\022\016\n\nSVT_DOUBLE"
      "\020\004\022\016\n\nSVT_STRING\020\005\022\014\n\010SVT_BOOL\020\006\"\'\n\024Upda"
      "teSensorResponse\022\017\n\007success\030\001 \001(\010\"\036\n\014Pin"
      "gResponse\022\016\n\006number\030\001 \001(\r\"\237\002\n\014SimuRespon"
      "se\022.\n\007connect\030\001 \001(\0132\033.open_vario.Connect"
      "ResponseH\000\0224\n\ndisconnect\030\002 \001(\0132\036.open_va"
      "rio.DisconnectResponseH\000\0227\n\014list_sensors"
      "\030\003 \001(\0132\037.open_vario.ListSensorsResponseH"
      "\000\0229\n\rupdate_sensor\030\004 \001(\0132 .open_vario.Up"
      "dateSensorResponseH\000\022(\n\004ping\030\005 \001(\0132\030.ope"
      "n_vario.PingResponseH\000B\013\n\tResponsesb\006pro"
      "to3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 923);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "responses.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_responses_2eproto
namespace open_vario {
const ::google::protobuf::EnumDescriptor* ListSensorsResponse_SensorType_descriptor() {
  protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_responses_2eproto::file_level_enum_descriptors[0];
}
bool ListSensorsResponse_SensorType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 8:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const ListSensorsResponse_SensorType ListSensorsResponse::ST_UNKNOWN;
const ListSensorsResponse_SensorType ListSensorsResponse::ST_PRESSURE;
const ListSensorsResponse_SensorType ListSensorsResponse::ST_TEMPERATURE;
const ListSensorsResponse_SensorType ListSensorsResponse::ST_ALTITUDE;
const ListSensorsResponse_SensorType ListSensorsResponse::ST_GNSS;
const ListSensorsResponse_SensorType ListSensorsResponse::SensorType_MIN;
const ListSensorsResponse_SensorType ListSensorsResponse::SensorType_MAX;
const int ListSensorsResponse::SensorType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* ListSensorsResponse_SensorValueType_descriptor() {
  protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_responses_2eproto::file_level_enum_descriptors[1];
}
bool ListSensorsResponse_SensorValueType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const ListSensorsResponse_SensorValueType ListSensorsResponse::SVT_UNKNOWN;
const ListSensorsResponse_SensorValueType ListSensorsResponse::SVT_UINT;
const ListSensorsResponse_SensorValueType ListSensorsResponse::SVT_INT;
const ListSensorsResponse_SensorValueType ListSensorsResponse::SVT_FLOAT;
const ListSensorsResponse_SensorValueType ListSensorsResponse::SVT_DOUBLE;
const ListSensorsResponse_SensorValueType ListSensorsResponse::SVT_STRING;
const ListSensorsResponse_SensorValueType ListSensorsResponse::SVT_BOOL;
const ListSensorsResponse_SensorValueType ListSensorsResponse::SensorValueType_MIN;
const ListSensorsResponse_SensorValueType ListSensorsResponse::SensorValueType_MAX;
const int ListSensorsResponse::SensorValueType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void ConnectResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConnectResponse::kAcceptFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConnectResponse::ConnectResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_responses_2eproto::scc_info_ConnectResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.ConnectResponse)
}
ConnectResponse::ConnectResponse(const ConnectResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  accept_ = from.accept_;
  // @@protoc_insertion_point(copy_constructor:open_vario.ConnectResponse)
}

void ConnectResponse::SharedCtor() {
  accept_ = false;
}

ConnectResponse::~ConnectResponse() {
  // @@protoc_insertion_point(destructor:open_vario.ConnectResponse)
  SharedDtor();
}

void ConnectResponse::SharedDtor() {
}

void ConnectResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ConnectResponse::descriptor() {
  ::protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ConnectResponse& ConnectResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_responses_2eproto::scc_info_ConnectResponse.base);
  return *internal_default_instance();
}


void ConnectResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.ConnectResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  accept_ = false;
  _internal_metadata_.Clear();
}

bool ConnectResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:open_vario.ConnectResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool accept = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &accept_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.ConnectResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.ConnectResponse)
  return false;
#undef DO_
}

void ConnectResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.ConnectResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool accept = 1;
  if (this->accept() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->accept(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:open_vario.ConnectResponse)
}

::google::protobuf::uint8* ConnectResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:open_vario.ConnectResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool accept = 1;
  if (this->accept() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->accept(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:open_vario.ConnectResponse)
  return target;
}

size_t ConnectResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.ConnectResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bool accept = 1;
  if (this->accept() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConnectResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:open_vario.ConnectResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ConnectResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ConnectResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:open_vario.ConnectResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:open_vario.ConnectResponse)
    MergeFrom(*source);
  }
}

void ConnectResponse::MergeFrom(const ConnectResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.ConnectResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.accept() != 0) {
    set_accept(from.accept());
  }
}

void ConnectResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:open_vario.ConnectResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConnectResponse::CopyFrom(const ConnectResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.ConnectResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConnectResponse::IsInitialized() const {
  return true;
}

void ConnectResponse::Swap(ConnectResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConnectResponse::InternalSwap(ConnectResponse* other) {
  using std::swap;
  swap(accept_, other->accept_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ConnectResponse::GetMetadata() const {
  protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DisconnectResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DisconnectResponse::DisconnectResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_responses_2eproto::scc_info_DisconnectResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.DisconnectResponse)
}
DisconnectResponse::DisconnectResponse(const DisconnectResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:open_vario.DisconnectResponse)
}

void DisconnectResponse::SharedCtor() {
}

DisconnectResponse::~DisconnectResponse() {
  // @@protoc_insertion_point(destructor:open_vario.DisconnectResponse)
  SharedDtor();
}

void DisconnectResponse::SharedDtor() {
}

void DisconnectResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DisconnectResponse::descriptor() {
  ::protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DisconnectResponse& DisconnectResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_responses_2eproto::scc_info_DisconnectResponse.base);
  return *internal_default_instance();
}


void DisconnectResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.DisconnectResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool DisconnectResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:open_vario.DisconnectResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.DisconnectResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.DisconnectResponse)
  return false;
#undef DO_
}

void DisconnectResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.DisconnectResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:open_vario.DisconnectResponse)
}

::google::protobuf::uint8* DisconnectResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:open_vario.DisconnectResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:open_vario.DisconnectResponse)
  return target;
}

size_t DisconnectResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.DisconnectResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DisconnectResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:open_vario.DisconnectResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const DisconnectResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DisconnectResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:open_vario.DisconnectResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:open_vario.DisconnectResponse)
    MergeFrom(*source);
  }
}

void DisconnectResponse::MergeFrom(const DisconnectResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.DisconnectResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void DisconnectResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:open_vario.DisconnectResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DisconnectResponse::CopyFrom(const DisconnectResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.DisconnectResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DisconnectResponse::IsInitialized() const {
  return true;
}

void DisconnectResponse::Swap(DisconnectResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DisconnectResponse::InternalSwap(DisconnectResponse* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DisconnectResponse::GetMetadata() const {
  protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ListSensorsResponse_Sensor::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ListSensorsResponse_Sensor::kIdFieldNumber;
const int ListSensorsResponse_Sensor::kNameFieldNumber;
const int ListSensorsResponse_Sensor::kTypeFieldNumber;
const int ListSensorsResponse_Sensor::kValueTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ListSensorsResponse_Sensor::ListSensorsResponse_Sensor()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_responses_2eproto::scc_info_ListSensorsResponse_Sensor.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.ListSensorsResponse.Sensor)
}
ListSensorsResponse_Sensor::ListSensorsResponse_Sensor(const ListSensorsResponse_Sensor& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&value_type_) -
    reinterpret_cast<char*>(&id_)) + sizeof(value_type_));
  // @@protoc_insertion_point(copy_constructor:open_vario.ListSensorsResponse.Sensor)
}

void ListSensorsResponse_Sensor::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_type_) -
      reinterpret_cast<char*>(&id_)) + sizeof(value_type_));
}

ListSensorsResponse_Sensor::~ListSensorsResponse_Sensor() {
  // @@protoc_insertion_point(destructor:open_vario.ListSensorsResponse.Sensor)
  SharedDtor();
}

void ListSensorsResponse_Sensor::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ListSensorsResponse_Sensor::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ListSensorsResponse_Sensor::descriptor() {
  ::protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ListSensorsResponse_Sensor& ListSensorsResponse_Sensor::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_responses_2eproto::scc_info_ListSensorsResponse_Sensor.base);
  return *internal_default_instance();
}


void ListSensorsResponse_Sensor::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.ListSensorsResponse.Sensor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_type_) -
      reinterpret_cast<char*>(&id_)) + sizeof(value_type_));
  _internal_metadata_.Clear();
}

bool ListSensorsResponse_Sensor::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:open_vario.ListSensorsResponse.Sensor)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "open_vario.ListSensorsResponse.Sensor.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .open_vario.ListSensorsResponse.SensorType type = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::open_vario::ListSensorsResponse_SensorType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .open_vario.ListSensorsResponse.SensorValueType value_type = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_value_type(static_cast< ::open_vario::ListSensorsResponse_SensorValueType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.ListSensorsResponse.Sensor)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.ListSensorsResponse.Sensor)
  return false;
#undef DO_
}

void ListSensorsResponse_Sensor::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.ListSensorsResponse.Sensor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "open_vario.ListSensorsResponse.Sensor.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // .open_vario.ListSensorsResponse.SensorType type = 3;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->type(), output);
  }

  // .open_vario.ListSensorsResponse.SensorValueType value_type = 4;
  if (this->value_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->value_type(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:open_vario.ListSensorsResponse.Sensor)
}

::google::protobuf::uint8* ListSensorsResponse_Sensor::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:open_vario.ListSensorsResponse.Sensor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "open_vario.ListSensorsResponse.Sensor.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // .open_vario.ListSensorsResponse.SensorType type = 3;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->type(), target);
  }

  // .open_vario.ListSensorsResponse.SensorValueType value_type = 4;
  if (this->value_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->value_type(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:open_vario.ListSensorsResponse.Sensor)
  return target;
}

size_t ListSensorsResponse_Sensor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.ListSensorsResponse.Sensor)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // uint32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->id());
  }

  // .open_vario.ListSensorsResponse.SensorType type = 3;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // .open_vario.ListSensorsResponse.SensorValueType value_type = 4;
  if (this->value_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->value_type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ListSensorsResponse_Sensor::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:open_vario.ListSensorsResponse.Sensor)
  GOOGLE_DCHECK_NE(&from, this);
  const ListSensorsResponse_Sensor* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ListSensorsResponse_Sensor>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:open_vario.ListSensorsResponse.Sensor)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:open_vario.ListSensorsResponse.Sensor)
    MergeFrom(*source);
  }
}

void ListSensorsResponse_Sensor::MergeFrom(const ListSensorsResponse_Sensor& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.ListSensorsResponse.Sensor)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.value_type() != 0) {
    set_value_type(from.value_type());
  }
}

void ListSensorsResponse_Sensor::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:open_vario.ListSensorsResponse.Sensor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ListSensorsResponse_Sensor::CopyFrom(const ListSensorsResponse_Sensor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.ListSensorsResponse.Sensor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListSensorsResponse_Sensor::IsInitialized() const {
  return true;
}

void ListSensorsResponse_Sensor::Swap(ListSensorsResponse_Sensor* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ListSensorsResponse_Sensor::InternalSwap(ListSensorsResponse_Sensor* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(id_, other->id_);
  swap(type_, other->type_);
  swap(value_type_, other->value_type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ListSensorsResponse_Sensor::GetMetadata() const {
  protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ListSensorsResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ListSensorsResponse::kSensorsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ListSensorsResponse::ListSensorsResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_responses_2eproto::scc_info_ListSensorsResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.ListSensorsResponse)
}
ListSensorsResponse::ListSensorsResponse(const ListSensorsResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      sensors_(from.sensors_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:open_vario.ListSensorsResponse)
}

void ListSensorsResponse::SharedCtor() {
}

ListSensorsResponse::~ListSensorsResponse() {
  // @@protoc_insertion_point(destructor:open_vario.ListSensorsResponse)
  SharedDtor();
}

void ListSensorsResponse::SharedDtor() {
}

void ListSensorsResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ListSensorsResponse::descriptor() {
  ::protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ListSensorsResponse& ListSensorsResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_responses_2eproto::scc_info_ListSensorsResponse.base);
  return *internal_default_instance();
}


void ListSensorsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.ListSensorsResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sensors_.Clear();
  _internal_metadata_.Clear();
}

bool ListSensorsResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:open_vario.ListSensorsResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .open_vario.ListSensorsResponse.Sensor sensors = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_sensors()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.ListSensorsResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.ListSensorsResponse)
  return false;
#undef DO_
}

void ListSensorsResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.ListSensorsResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .open_vario.ListSensorsResponse.Sensor sensors = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->sensors_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->sensors(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:open_vario.ListSensorsResponse)
}

::google::protobuf::uint8* ListSensorsResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:open_vario.ListSensorsResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .open_vario.ListSensorsResponse.Sensor sensors = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->sensors_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->sensors(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:open_vario.ListSensorsResponse)
  return target;
}

size_t ListSensorsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.ListSensorsResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .open_vario.ListSensorsResponse.Sensor sensors = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->sensors_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->sensors(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ListSensorsResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:open_vario.ListSensorsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ListSensorsResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ListSensorsResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:open_vario.ListSensorsResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:open_vario.ListSensorsResponse)
    MergeFrom(*source);
  }
}

void ListSensorsResponse::MergeFrom(const ListSensorsResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.ListSensorsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  sensors_.MergeFrom(from.sensors_);
}

void ListSensorsResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:open_vario.ListSensorsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ListSensorsResponse::CopyFrom(const ListSensorsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.ListSensorsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListSensorsResponse::IsInitialized() const {
  return true;
}

void ListSensorsResponse::Swap(ListSensorsResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ListSensorsResponse::InternalSwap(ListSensorsResponse* other) {
  using std::swap;
  CastToBase(&sensors_)->InternalSwap(CastToBase(&other->sensors_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ListSensorsResponse::GetMetadata() const {
  protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void UpdateSensorResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UpdateSensorResponse::kSuccessFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UpdateSensorResponse::UpdateSensorResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_responses_2eproto::scc_info_UpdateSensorResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.UpdateSensorResponse)
}
UpdateSensorResponse::UpdateSensorResponse(const UpdateSensorResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  success_ = from.success_;
  // @@protoc_insertion_point(copy_constructor:open_vario.UpdateSensorResponse)
}

void UpdateSensorResponse::SharedCtor() {
  success_ = false;
}

UpdateSensorResponse::~UpdateSensorResponse() {
  // @@protoc_insertion_point(destructor:open_vario.UpdateSensorResponse)
  SharedDtor();
}

void UpdateSensorResponse::SharedDtor() {
}

void UpdateSensorResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* UpdateSensorResponse::descriptor() {
  ::protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UpdateSensorResponse& UpdateSensorResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_responses_2eproto::scc_info_UpdateSensorResponse.base);
  return *internal_default_instance();
}


void UpdateSensorResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.UpdateSensorResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  success_ = false;
  _internal_metadata_.Clear();
}

bool UpdateSensorResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:open_vario.UpdateSensorResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool success = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &success_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.UpdateSensorResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.UpdateSensorResponse)
  return false;
#undef DO_
}

void UpdateSensorResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.UpdateSensorResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->success() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->success(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:open_vario.UpdateSensorResponse)
}

::google::protobuf::uint8* UpdateSensorResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:open_vario.UpdateSensorResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->success() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->success(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:open_vario.UpdateSensorResponse)
  return target;
}

size_t UpdateSensorResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.UpdateSensorResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bool success = 1;
  if (this->success() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UpdateSensorResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:open_vario.UpdateSensorResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const UpdateSensorResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UpdateSensorResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:open_vario.UpdateSensorResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:open_vario.UpdateSensorResponse)
    MergeFrom(*source);
  }
}

void UpdateSensorResponse::MergeFrom(const UpdateSensorResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.UpdateSensorResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.success() != 0) {
    set_success(from.success());
  }
}

void UpdateSensorResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:open_vario.UpdateSensorResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UpdateSensorResponse::CopyFrom(const UpdateSensorResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.UpdateSensorResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateSensorResponse::IsInitialized() const {
  return true;
}

void UpdateSensorResponse::Swap(UpdateSensorResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UpdateSensorResponse::InternalSwap(UpdateSensorResponse* other) {
  using std::swap;
  swap(success_, other->success_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata UpdateSensorResponse::GetMetadata() const {
  protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PingResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PingResponse::kNumberFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PingResponse::PingResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_responses_2eproto::scc_info_PingResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.PingResponse)
}
PingResponse::PingResponse(const PingResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  number_ = from.number_;
  // @@protoc_insertion_point(copy_constructor:open_vario.PingResponse)
}

void PingResponse::SharedCtor() {
  number_ = 0u;
}

PingResponse::~PingResponse() {
  // @@protoc_insertion_point(destructor:open_vario.PingResponse)
  SharedDtor();
}

void PingResponse::SharedDtor() {
}

void PingResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PingResponse::descriptor() {
  ::protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PingResponse& PingResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_responses_2eproto::scc_info_PingResponse.base);
  return *internal_default_instance();
}


void PingResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.PingResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  number_ = 0u;
  _internal_metadata_.Clear();
}

bool PingResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:open_vario.PingResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 number = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &number_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.PingResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.PingResponse)
  return false;
#undef DO_
}

void PingResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.PingResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 number = 1;
  if (this->number() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->number(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:open_vario.PingResponse)
}

::google::protobuf::uint8* PingResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:open_vario.PingResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 number = 1;
  if (this->number() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->number(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:open_vario.PingResponse)
  return target;
}

size_t PingResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.PingResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 number = 1;
  if (this->number() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->number());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PingResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:open_vario.PingResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const PingResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PingResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:open_vario.PingResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:open_vario.PingResponse)
    MergeFrom(*source);
  }
}

void PingResponse::MergeFrom(const PingResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.PingResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.number() != 0) {
    set_number(from.number());
  }
}

void PingResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:open_vario.PingResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PingResponse::CopyFrom(const PingResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.PingResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PingResponse::IsInitialized() const {
  return true;
}

void PingResponse::Swap(PingResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PingResponse::InternalSwap(PingResponse* other) {
  using std::swap;
  swap(number_, other->number_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PingResponse::GetMetadata() const {
  protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SimuResponse::InitAsDefaultInstance() {
  ::open_vario::_SimuResponse_default_instance_.connect_ = const_cast< ::open_vario::ConnectResponse*>(
      ::open_vario::ConnectResponse::internal_default_instance());
  ::open_vario::_SimuResponse_default_instance_.disconnect_ = const_cast< ::open_vario::DisconnectResponse*>(
      ::open_vario::DisconnectResponse::internal_default_instance());
  ::open_vario::_SimuResponse_default_instance_.list_sensors_ = const_cast< ::open_vario::ListSensorsResponse*>(
      ::open_vario::ListSensorsResponse::internal_default_instance());
  ::open_vario::_SimuResponse_default_instance_.update_sensor_ = const_cast< ::open_vario::UpdateSensorResponse*>(
      ::open_vario::UpdateSensorResponse::internal_default_instance());
  ::open_vario::_SimuResponse_default_instance_.ping_ = const_cast< ::open_vario::PingResponse*>(
      ::open_vario::PingResponse::internal_default_instance());
}
void SimuResponse::set_allocated_connect(::open_vario::ConnectResponse* connect) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_Responses();
  if (connect) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      connect = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, connect, submessage_arena);
    }
    set_has_connect();
    Responses_.connect_ = connect;
  }
  // @@protoc_insertion_point(field_set_allocated:open_vario.SimuResponse.connect)
}
void SimuResponse::set_allocated_disconnect(::open_vario::DisconnectResponse* disconnect) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_Responses();
  if (disconnect) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      disconnect = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, disconnect, submessage_arena);
    }
    set_has_disconnect();
    Responses_.disconnect_ = disconnect;
  }
  // @@protoc_insertion_point(field_set_allocated:open_vario.SimuResponse.disconnect)
}
void SimuResponse::set_allocated_list_sensors(::open_vario::ListSensorsResponse* list_sensors) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_Responses();
  if (list_sensors) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      list_sensors = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, list_sensors, submessage_arena);
    }
    set_has_list_sensors();
    Responses_.list_sensors_ = list_sensors;
  }
  // @@protoc_insertion_point(field_set_allocated:open_vario.SimuResponse.list_sensors)
}
void SimuResponse::set_allocated_update_sensor(::open_vario::UpdateSensorResponse* update_sensor) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_Responses();
  if (update_sensor) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      update_sensor = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, update_sensor, submessage_arena);
    }
    set_has_update_sensor();
    Responses_.update_sensor_ = update_sensor;
  }
  // @@protoc_insertion_point(field_set_allocated:open_vario.SimuResponse.update_sensor)
}
void SimuResponse::set_allocated_ping(::open_vario::PingResponse* ping) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_Responses();
  if (ping) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      ping = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, ping, submessage_arena);
    }
    set_has_ping();
    Responses_.ping_ = ping;
  }
  // @@protoc_insertion_point(field_set_allocated:open_vario.SimuResponse.ping)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SimuResponse::kConnectFieldNumber;
const int SimuResponse::kDisconnectFieldNumber;
const int SimuResponse::kListSensorsFieldNumber;
const int SimuResponse::kUpdateSensorFieldNumber;
const int SimuResponse::kPingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SimuResponse::SimuResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_responses_2eproto::scc_info_SimuResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:open_vario.SimuResponse)
}
SimuResponse::SimuResponse(const SimuResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_Responses();
  switch (from.Responses_case()) {
    case kConnect: {
      mutable_connect()->::open_vario::ConnectResponse::MergeFrom(from.connect());
      break;
    }
    case kDisconnect: {
      mutable_disconnect()->::open_vario::DisconnectResponse::MergeFrom(from.disconnect());
      break;
    }
    case kListSensors: {
      mutable_list_sensors()->::open_vario::ListSensorsResponse::MergeFrom(from.list_sensors());
      break;
    }
    case kUpdateSensor: {
      mutable_update_sensor()->::open_vario::UpdateSensorResponse::MergeFrom(from.update_sensor());
      break;
    }
    case kPing: {
      mutable_ping()->::open_vario::PingResponse::MergeFrom(from.ping());
      break;
    }
    case RESPONSES_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:open_vario.SimuResponse)
}

void SimuResponse::SharedCtor() {
  clear_has_Responses();
}

SimuResponse::~SimuResponse() {
  // @@protoc_insertion_point(destructor:open_vario.SimuResponse)
  SharedDtor();
}

void SimuResponse::SharedDtor() {
  if (has_Responses()) {
    clear_Responses();
  }
}

void SimuResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SimuResponse::descriptor() {
  ::protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SimuResponse& SimuResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_responses_2eproto::scc_info_SimuResponse.base);
  return *internal_default_instance();
}


void SimuResponse::clear_Responses() {
// @@protoc_insertion_point(one_of_clear_start:open_vario.SimuResponse)
  switch (Responses_case()) {
    case kConnect: {
      delete Responses_.connect_;
      break;
    }
    case kDisconnect: {
      delete Responses_.disconnect_;
      break;
    }
    case kListSensors: {
      delete Responses_.list_sensors_;
      break;
    }
    case kUpdateSensor: {
      delete Responses_.update_sensor_;
      break;
    }
    case kPing: {
      delete Responses_.ping_;
      break;
    }
    case RESPONSES_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = RESPONSES_NOT_SET;
}


void SimuResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:open_vario.SimuResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_Responses();
  _internal_metadata_.Clear();
}

bool SimuResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:open_vario.SimuResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .open_vario.ConnectResponse connect = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_connect()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .open_vario.DisconnectResponse disconnect = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_disconnect()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .open_vario.ListSensorsResponse list_sensors = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_list_sensors()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .open_vario.UpdateSensorResponse update_sensor = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_update_sensor()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .open_vario.PingResponse ping = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_ping()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:open_vario.SimuResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:open_vario.SimuResponse)
  return false;
#undef DO_
}

void SimuResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:open_vario.SimuResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .open_vario.ConnectResponse connect = 1;
  if (has_connect()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_connect(), output);
  }

  // .open_vario.DisconnectResponse disconnect = 2;
  if (has_disconnect()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_disconnect(), output);
  }

  // .open_vario.ListSensorsResponse list_sensors = 3;
  if (has_list_sensors()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_list_sensors(), output);
  }

  // .open_vario.UpdateSensorResponse update_sensor = 4;
  if (has_update_sensor()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_internal_update_sensor(), output);
  }

  // .open_vario.PingResponse ping = 5;
  if (has_ping()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->_internal_ping(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:open_vario.SimuResponse)
}

::google::protobuf::uint8* SimuResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:open_vario.SimuResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .open_vario.ConnectResponse connect = 1;
  if (has_connect()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_connect(), deterministic, target);
  }

  // .open_vario.DisconnectResponse disconnect = 2;
  if (has_disconnect()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_disconnect(), deterministic, target);
  }

  // .open_vario.ListSensorsResponse list_sensors = 3;
  if (has_list_sensors()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_list_sensors(), deterministic, target);
  }

  // .open_vario.UpdateSensorResponse update_sensor = 4;
  if (has_update_sensor()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->_internal_update_sensor(), deterministic, target);
  }

  // .open_vario.PingResponse ping = 5;
  if (has_ping()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->_internal_ping(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:open_vario.SimuResponse)
  return target;
}

size_t SimuResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:open_vario.SimuResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  switch (Responses_case()) {
    // .open_vario.ConnectResponse connect = 1;
    case kConnect: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *Responses_.connect_);
      break;
    }
    // .open_vario.DisconnectResponse disconnect = 2;
    case kDisconnect: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *Responses_.disconnect_);
      break;
    }
    // .open_vario.ListSensorsResponse list_sensors = 3;
    case kListSensors: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *Responses_.list_sensors_);
      break;
    }
    // .open_vario.UpdateSensorResponse update_sensor = 4;
    case kUpdateSensor: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *Responses_.update_sensor_);
      break;
    }
    // .open_vario.PingResponse ping = 5;
    case kPing: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *Responses_.ping_);
      break;
    }
    case RESPONSES_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SimuResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:open_vario.SimuResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const SimuResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SimuResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:open_vario.SimuResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:open_vario.SimuResponse)
    MergeFrom(*source);
  }
}

void SimuResponse::MergeFrom(const SimuResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:open_vario.SimuResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.Responses_case()) {
    case kConnect: {
      mutable_connect()->::open_vario::ConnectResponse::MergeFrom(from.connect());
      break;
    }
    case kDisconnect: {
      mutable_disconnect()->::open_vario::DisconnectResponse::MergeFrom(from.disconnect());
      break;
    }
    case kListSensors: {
      mutable_list_sensors()->::open_vario::ListSensorsResponse::MergeFrom(from.list_sensors());
      break;
    }
    case kUpdateSensor: {
      mutable_update_sensor()->::open_vario::UpdateSensorResponse::MergeFrom(from.update_sensor());
      break;
    }
    case kPing: {
      mutable_ping()->::open_vario::PingResponse::MergeFrom(from.ping());
      break;
    }
    case RESPONSES_NOT_SET: {
      break;
    }
  }
}

void SimuResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:open_vario.SimuResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SimuResponse::CopyFrom(const SimuResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:open_vario.SimuResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimuResponse::IsInitialized() const {
  return true;
}

void SimuResponse::Swap(SimuResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SimuResponse::InternalSwap(SimuResponse* other) {
  using std::swap;
  swap(Responses_, other->Responses_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SimuResponse::GetMetadata() const {
  protobuf_responses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_responses_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace open_vario
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::ConnectResponse* Arena::CreateMaybeMessage< ::open_vario::ConnectResponse >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::ConnectResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::DisconnectResponse* Arena::CreateMaybeMessage< ::open_vario::DisconnectResponse >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::DisconnectResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::ListSensorsResponse_Sensor* Arena::CreateMaybeMessage< ::open_vario::ListSensorsResponse_Sensor >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::ListSensorsResponse_Sensor >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::ListSensorsResponse* Arena::CreateMaybeMessage< ::open_vario::ListSensorsResponse >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::ListSensorsResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::UpdateSensorResponse* Arena::CreateMaybeMessage< ::open_vario::UpdateSensorResponse >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::UpdateSensorResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::PingResponse* Arena::CreateMaybeMessage< ::open_vario::PingResponse >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::PingResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::open_vario::SimuResponse* Arena::CreateMaybeMessage< ::open_vario::SimuResponse >(Arena* arena) {
  return Arena::CreateInternal< ::open_vario::SimuResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
